-- ==============================================================================
-- Honest Funeral — PRODUCTION DATABASE BOOTSTRAP
-- GENERATED by scripts/build-bootstrap-sql.mjs — do not hand-edit.
-- Re-generate:  node scripts/build-bootstrap-sql.mjs
--
-- HOW TO USE: open a fresh prod Supabase project → SQL Editor → paste this
-- ENTIRE file → Run. It applies schema.sql then every migration in order.
-- Idempotent, so safe to re-run. See docs/PROD_SETUP.md for the full checklist
-- (storage bucket, magic-link auth, env vars, DNS) — this file is just the DB.
-- ==============================================================================


-- ==============================================================================
-- schema.sql
-- ==============================================================================

-- Walk Beside — Supabase schema
-- Run this once in the SQL editor of your Supabase project.
-- Idempotent: safe to re-run.

-- ---------------------------------------------------------------------------
-- Profiles (mirrors auth.users)
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  zip text,
  scenario text,
  deceased_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop policy if exists "profiles_self_read" on public.profiles;
create policy "profiles_self_read" on public.profiles
  for select using (auth.uid() = id);

drop policy if exists "profiles_self_write" on public.profiles;
create policy "profiles_self_write" on public.profiles
  for all using (auth.uid() = id) with check (auth.uid() = id);

-- Auto-create profile on signup
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer as $$
begin
  insert into public.profiles (id) values (new.id) on conflict do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- Tasks (the dashboard's three-tasks-at-a-time list)
-- ---------------------------------------------------------------------------
create table if not exists public.tasks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  phase text not null,                 -- 'first-steps' | 'funeral' | 'service' | 'documents' | 'estate'
  title text not null,
  detail text,
  href text,
  status text not null default 'open', -- 'open' | 'done'
  position int not null default 0,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists tasks_user_status_idx on public.tasks (user_id, status, position);

alter table public.tasks enable row level security;
drop policy if exists "tasks_owner" on public.tasks;
create policy "tasks_owner" on public.tasks
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- Negotiations
-- ---------------------------------------------------------------------------
create table if not exists public.negotiations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  zip text not null,
  service_type text not null,
  target_home_name text,           -- specific home the family is considering
  target_home_estimate_cents int,  -- price they were quoted (if any)
  status text not null default 'started', -- 'started' | 'pending_payment' | 'contacting' | 'received' | 'closed' | 'cancelled' | 'no_homes_available'
  best_quote_cents int,
  savings_cents int,
  fee_cents int,
  stripe_setup_intent_id text,
  stripe_payment_intent_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists negotiations_user_idx on public.negotiations (user_id, created_at desc);

alter table public.negotiations enable row level security;
drop policy if exists "negotiations_owner" on public.negotiations;
create policy "negotiations_owner" on public.negotiations
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- Negotiation outreach (one row per funeral home contacted)
-- ---------------------------------------------------------------------------
create table if not exists public.negotiation_outreach (
  id uuid primary key default gen_random_uuid(),
  negotiation_id uuid not null references public.negotiations(id) on delete cascade,
  home_name text not null,
  home_email text,
  initial_email_id text,
  initial_email_body text,
  quote_cents int,
  notes text,
  status text not null default 'pending', -- 'pending' (stored, not yet sent) | 'sent' | 'dry_run' | 'replied' | 'no-reply' | 'declined'
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.negotiation_outreach enable row level security;
drop policy if exists "outreach_owner" on public.negotiation_outreach;
create policy "outreach_owner" on public.negotiation_outreach
  for all using (
    auth.uid() = (select user_id from public.negotiations where id = negotiation_id)
  );

-- ---------------------------------------------------------------------------
-- Price list analyses
-- ---------------------------------------------------------------------------
create table if not exists public.price_list_analyses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  raw_text text,
  total_quoted_cents int,
  total_fair_cents int,
  potential_savings_cents int,
  items jsonb,
  zip text,                        -- regional benchmark aggregation (2026-07-02-benchmark-zip.sql)
  created_at timestamptz not null default now()
);

alter table public.price_list_analyses enable row level security;
drop policy if exists "analyses_owner" on public.price_list_analyses;
create policy "analyses_owner" on public.price_list_analyses
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- Death certificate trackers
-- ---------------------------------------------------------------------------
create table if not exists public.cert_trackers (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  total_to_order int not null default 0,
  ordered int not null default 0,
  recipients jsonb,                -- [{ name, mailed_at, received_at }]
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.cert_trackers enable row level security;
drop policy if exists "certs_owner" on public.cert_trackers;
create policy "certs_owner" on public.cert_trackers
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- Obituary drafts
-- ---------------------------------------------------------------------------
create table if not exists public.obituaries (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  inputs jsonb,
  draft text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.obituaries enable row level security;
drop policy if exists "obits_owner" on public.obituaries;
create policy "obits_owner" on public.obituaries
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- Planning-ahead email list (cheat sheet signups, pre-need lead capture)
-- Segmented marketing list — never mixed with case / at-need emails.
-- ---------------------------------------------------------------------------
create table if not exists public.planning_signups (
  id uuid primary key default gen_random_uuid(),
  email text not null,
  source text not null default 'cheatsheet',
  zip text,
  ip_hash text,
  user_agent text,
  created_at timestamptz not null default now(),
  unique (email, source)
);

alter table public.planning_signups enable row level security;
-- Anonymous inserts only (no select, no update, no delete from the client).
drop policy if exists "planning_signups_insert_anon" on public.planning_signups;
create policy "planning_signups_insert_anon" on public.planning_signups
  for insert to anon, authenticated with check (true);

-- ---------------------------------------------------------------------------
-- Storage bucket for uploaded price lists (create manually in Dashboard or via this hint)
-- ---------------------------------------------------------------------------
-- In Supabase: Storage → New bucket → name "price-lists", private.


-- ==============================================================================
-- migrations/2026-04-25-v2-unlock-and-directory.sql
-- ==============================================================================

-- V2 migration: pure $49 unlock flow + funeral home directory.
-- Run this once in Supabase SQL editor after schema.sql. Idempotent.

-- ---------------------------------------------------------------------------
-- Unlock timestamp on negotiations.
-- Set when the family pays the $49 advocate fee. Until set, dashboard blurs
-- home names. Independent from `status='closed'` (closed = deal finalized;
-- unlocked = paid to see the data).
-- ---------------------------------------------------------------------------
alter table public.negotiations
  add column if not exists unlocked_at timestamptz;

-- ---------------------------------------------------------------------------
-- Funeral home directory.
-- Sister-curated for launch city. Read-only for end users; written by service
-- role only (admin tools / SQL editor).
-- ---------------------------------------------------------------------------
create table if not exists public.funeral_homes (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text,                         -- outreach destination; null = exclude from outreach
  phone text,
  address text,
  city text,
  state text,                         -- 2-letter, uppercase
  zip text,
  lat double precision,
  lng double precision,
  google_rating numeric(2,1),         -- 0.0 to 5.0
  google_review_count int,
  notes text,                         -- internal notes (sister)
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists funeral_homes_zip_idx on public.funeral_homes (zip);
create index if not exists funeral_homes_state_active_idx on public.funeral_homes (state, active);

alter table public.funeral_homes enable row level security;

-- Public read of active homes — directory is not sensitive.
drop policy if exists "funeral_homes_public_read" on public.funeral_homes;
create policy "funeral_homes_public_read" on public.funeral_homes
  for select using (active = true);

-- No public write. Service role bypasses RLS, so admin updates work via the
-- SQL editor or service-role-keyed scripts.


-- ==============================================================================
-- migrations/2026-04-26-v1.5-quote-items.sql
-- ==============================================================================

-- Adds itemized quote storage on outreach rows so the side-by-side
-- /negotiate/[id]/compare page can show line-item-level comparisons
-- (and color-code each cell vs the fair-price range) instead of only
-- the all-in total quote_cents the V2 schema captures today.
--
-- Until we build a quote-entry form, sister enters this manually in the
-- Supabase Table Editor as JSON of the form:
--
--   [
--     { "lineItemId": "basic-services", "name": "Basic services fee", "cents": 240000 },
--     { "lineItemId": "casket-wood",    "name": "Casket — wood",      "cents": 180000 },
--     ...
--   ]
--
-- `lineItemId` should match an `id` from lib/pricing-data.ts when possible —
-- the comparison view uses that to classify each cell as good / fair / high /
-- predatory. Items that don't match a known id still display, just without
-- a fair-range badge.

alter table public.negotiation_outreach
  add column if not exists quote_items jsonb;

comment on column public.negotiation_outreach.quote_items is
  'Optional itemized quote, shape: [{lineItemId, name, cents}]. Powers /negotiate/[id]/compare cell-level fair-price ratings.';


-- ==============================================================================
-- migrations/2026-05-05-margaret-share-links.sql
-- ==============================================================================

-- Share-link table for the "Save for my daughter" feature.
--
-- A share link snapshots the originating user's relevant sessionStorage
-- state (faith, decide answers, negotiate-wizard state) and gives them
-- a URL they can text to a family member. Both ends are anonymous —
-- no login required for either originator or recipient.
--
-- Privacy: links expire in 7 days. No PII in the URL — just the UUID.
-- The payload is a JSONB blob the client wrote; the server only stores
-- and returns it.

create table if not exists public.share_links (
  id uuid primary key default gen_random_uuid(),
  payload jsonb not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '7 days'),
  opened_at timestamptz
);

create index if not exists share_links_expires_at_idx
  on public.share_links (expires_at);

comment on table public.share_links is
  'Margaret-section-7: anonymous share links for "Save for my daughter" handoff. Auto-expire after 7 days.';

-- RLS: anyone can read by id (the URL token IS the auth), anyone can
-- insert. We rely on the unguessable UUID for security; expired rows
-- return null from the read endpoint.
alter table public.share_links enable row level security;

drop policy if exists "anyone can create share links" on public.share_links;
create policy "anyone can create share links"
  on public.share_links
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "anyone can read non-expired share links" on public.share_links;
create policy "anyone can read non-expired share links"
  on public.share_links
  for select
  to anon, authenticated
  using (expires_at > now());

drop policy if exists "anyone can update opened_at" on public.share_links;
create policy "anyone can update opened_at"
  on public.share_links
  for update
  to anon, authenticated
  using (expires_at > now())
  with check (expires_at > now());


-- ==============================================================================
-- migrations/2026-05-08-margaret-paywall.sql
-- ==============================================================================

-- Add account-level paywall fields to profiles.
--
-- Margaret refactor section 12: payment moves from per-negotiation success
-- fee to one-time $49 upfront unlock for the full toolkit.
--
-- paid_at is the source of truth. NULL = unpaid. Set by the Stripe webhook
-- when the user completes the account-paywall checkout. Once set, the user
-- has access to every paid surface (dashboard, negotiate, next-30-days,
-- worksheet, obituary, certificates, analyzer, veterans).
--
-- stripe_customer_id is set the first time we create a Checkout session
-- for this profile. Used for refund handling later.

alter table public.profiles
  add column if not exists paid_at timestamptz,
  add column if not exists stripe_customer_id text;

comment on column public.profiles.paid_at is
  'Margaret-section-12: timestamp of the user''s one-time $49 paywall purchase. NULL = unpaid. Source of truth for isPaidUser().';
comment on column public.profiles.stripe_customer_id is
  'Margaret-section-12: Stripe customer id, set on first Checkout session create. Used for refund flow.';

create index if not exists profiles_paid_at_idx on public.profiles (paid_at);


-- ==============================================================================
-- migrations/2026-05-09-margaret-anniversary-checkins.sql
-- ==============================================================================

-- Anniversary check-ins for the user's first month/six months/year
-- after they unlocked the toolkit. Margaret refactor section: long-term
-- relationship — turn one-time customers into trusted infrastructure.
--
-- The Vercel cron at /api/cron/anniversary runs daily, finds users whose
-- paid_at hits the appropriate window (≥30/180/365 days ago), sends the
-- corresponding email via Resend, and records it in
-- anniversary_emails_sent so we don't double-send.
--
-- Opt-in by default. Each email includes an unsubscribe link that hits
-- /preferences/[token] and flips the toggle to false.

alter table public.profiles
  add column if not exists anniversary_emails_opt_in boolean default true,
  add column if not exists anniversary_emails_sent jsonb default '[]'::jsonb;

comment on column public.profiles.anniversary_emails_opt_in is
  'Margaret-section-26: opt-in for 1mo/6mo/1yr post-paywall check-in emails. Default true; user can opt out via /preferences link in any email.';
comment on column public.profiles.anniversary_emails_sent is
  'Margaret-section-26: array of milestones already emailed: ["1mo", "6mo", "1yr"]. Prevents double-send when the cron runs daily.';

create index if not exists profiles_anniversary_idx
  on public.profiles (paid_at, anniversary_emails_opt_in)
  where paid_at is not null;


-- ==============================================================================
-- migrations/2026-05-09-margaret-quote-notifications.sql
-- ==============================================================================

-- Track when we've notified the family that a quote arrived from a
-- funeral home. The hourly cron at /api/cron/quote-notifications
-- watches for outreach rows that have a real quote (quote_cents or
-- quote_items populated) but no notified_at yet, sends the family
-- an email, and marks the row as notified to prevent re-sends.
--
-- Margaret refactor section: closes the loop on the V2 outreach
-- pipeline. Sister enters quotes (manually or via Resend webhook
-- in a future PR); the cron tells the family without us having to
-- watch the inbox.

alter table public.negotiation_outreach
  add column if not exists notified_at timestamptz;

comment on column public.negotiation_outreach.notified_at is
  'Margaret-section-27: timestamp the family was emailed about this quote arriving. NULL = not yet notified.';

create index if not exists outreach_notified_idx
  on public.negotiation_outreach (notified_at, quote_cents)
  where quote_cents is not null;


-- ==============================================================================
-- migrations/2026-05-16-nurture-emails.sql
-- ==============================================================================

-- Nurture-email tracking for planning_signups.
--
-- Welcome email already fires on signup (see /api/planning/signup).
-- This migration adds the per-row state needed to send two follow-up
-- nurture emails (step 1 at +7 days, step 2 at +21 days) and supports
-- a one-click unsubscribe.
--
-- Schedule lives in vercel.json; the cron route at
-- /api/cron/nurture-emails reads these columns and advances them.

alter table public.planning_signups
  add column if not exists nurture_step int not null default 0,
  add column if not exists last_nurture_sent_at timestamptz,
  add column if not exists unsubscribed_at timestamptz;

-- Partial index for the cron query: "rows still eligible for nurture
-- (not unsubscribed) ordered by readiness." Keeps the daily scan
-- cheap as the list grows.
create index if not exists planning_signups_nurture_due_idx
  on public.planning_signups (nurture_step, last_nurture_sent_at, created_at)
  where unsubscribed_at is null;


-- ==============================================================================
-- migrations/2026-05-21-coordinator-messages.sql
-- ==============================================================================

-- Coordinator-flow message thread.
-- Captures inbound (FD → us via Postmark Inbound) and outbound (us → FD, us → family)
-- messages tied to a negotiation, so the family never has to email the
-- funeral home directly. Read-side surfaces on /negotiate/[id]/status.

create table if not exists public.negotiation_messages (
  id uuid primary key default gen_random_uuid(),
  negotiation_id uuid not null references public.negotiations(id) on delete cascade,
  outreach_id uuid references public.negotiation_outreach(id) on delete set null,
  direction text not null check (
    direction in ('inbound_fd', 'outbound_to_fd', 'outbound_to_family')
  ),
  from_address text,
  to_address text,
  subject text,
  body_text text,
  body_html text,
  raw_payload jsonb,           -- entire provider webhook payload for debugging
  inbound_provider text,        -- 'postmark' for V1; other providers if/when we add them
  inbound_message_id text,      -- provider's Message-ID for dedup on retries
  delivered_at timestamptz,     -- when the outbound send was confirmed; null for inbound
  created_at timestamptz not null default now()
);

create index if not exists negotiation_messages_neg_idx
  on public.negotiation_messages (negotiation_id, created_at desc);

-- Unique partial index — dedupes inbound webhook retries from Postmark
create unique index if not exists negotiation_messages_inbound_id_idx
  on public.negotiation_messages (inbound_message_id)
  where inbound_message_id is not null;

alter table public.negotiation_messages enable row level security;

-- Family can read all messages on their own negotiation
drop policy if exists "negotiation_messages_owner_read" on public.negotiation_messages;
create policy "negotiation_messages_owner_read" on public.negotiation_messages
  for select using (
    exists (
      select 1 from public.negotiations n
      where n.id = negotiation_messages.negotiation_id
        and n.user_id = auth.uid()
    )
  );

-- Family can insert outbound_to_fd messages on their own negotiation;
-- the application layer enforces the direction constraint and triggers
-- the outbound send. Service role bypasses RLS for inbound webhook writes.
drop policy if exists "negotiation_messages_owner_send" on public.negotiation_messages;
create policy "negotiation_messages_owner_send" on public.negotiation_messages
  for insert with check (
    direction = 'outbound_to_fd'
    and exists (
      select 1 from public.negotiations n
      where n.id = negotiation_messages.negotiation_id
        and n.user_id = auth.uid()
    )
  );


-- ==============================================================================
-- migrations/2026-06-03-funeral-home-vetting.sql
-- ==============================================================================

-- Funeral home vetting: explicit sister-approval before any outreach.
-- Run this once in the Supabase SQL editor. Idempotent.
--
-- Why: until now the only gate on outreach was `active` (defaults true) +
-- a non-null email, so every imported row was outreach-eligible the moment
-- it landed. That is the wrong default for contacting real businesses. This
-- adds an explicit `vetted` flag that a licensed funeral director must set
-- per home. `findHomesFromDirectory` now requires `vetted = true`, so an
-- unreviewed home can never be contacted even if OUTREACH_LIVE is on.
--
-- Two independent flags, both required to contact a home:
--   active  — home is in good standing (auto-set false on bounce/complaint,
--             or manually when a home opts out). Gates public read (RLS).
--   vetted  — a human reviewed the row (correct email, real business, in our
--             launch area). Defaults FALSE so existing rows must be reviewed.

alter table public.funeral_homes
  add column if not exists vetted boolean not null default false;

alter table public.funeral_homes
  add column if not exists vetted_at timestamptz;

alter table public.funeral_homes
  add column if not exists vetted_by text;   -- reviewer label (e.g. "sarah")

-- Speeds the directory read (filters on vetted + active) and the admin
-- vetting page (filters by state + status).
create index if not exists funeral_homes_vetted_idx
  on public.funeral_homes (vetted, active);
create index if not exists funeral_homes_state_vetted_idx
  on public.funeral_homes (state, vetted);

-- NOTE: existing rows are now vetted = false. They will NOT appear in
-- outreach until reviewed and approved in /admin/vetting. This is intended:
-- no real funeral home is contacted until a human signs off.


-- ==============================================================================
-- migrations/2026-06-09-rls-hardening.sql
-- ==============================================================================

-- RLS / privilege hardening (2026-06-09). Idempotent; safe to re-run.
--
-- Findings from a pre-launch security pass on funeral_homes and
-- negotiation_messages:
--
-- 1. funeral_homes is publicly readable (RLS policy "funeral_homes_public_read"
--    = `for select using (active = true)`) so the directory works. But RLS is
--    ROW-level — it cannot hide COLUMNS. The public API roles (anon,
--    authenticated) hold a table-wide SELECT grant, so internal-only fields
--    (notes — sister/vetting commentary; vetted_by; vetted_at) were readable by
--    anyone holding the public anon key, not just the app.
--
--    Fix: drop the table-wide SELECT grant and re-grant SELECT only on the
--    non-internal columns. The directory read (lib/negotiation/directory.ts)
--    needs only name/email/zip; admin tools read the full row via the
--    service-role key, which BYPASSES these grants and RLS entirely. So nothing
--    the app does breaks, but a raw anon/authenticated query can no longer read
--    notes/vetted_by/vetted_at.
--
-- 2. funeral_homes and negotiation_messages intentionally have NO delete (and
--    no public write) policy. Under RLS, "no policy" = DENY — which is the
--    correct, safe default here:
--      - funeral_homes is a service-role/admin-managed directory (imports,
--        vetting, opt-out, bounce handling all run with the service-role key).
--      - negotiation_messages is a shared family<->home conversation/audit log;
--        neither side should be able to delete from the other's thread.
--    We deliberately DO NOT add permissive DELETE policies — that would be a
--    regression. This file documents the decision and re-asserts the intended
--    policies idempotently.

-- ---------------------------------------------------------------------------
-- 1. funeral_homes: column-level read hardening
-- ---------------------------------------------------------------------------
revoke select on public.funeral_homes from anon;
revoke select on public.funeral_homes from authenticated;

grant select (
  id, name, email, phone, address, city, state, zip,
  lat, lng, google_rating, google_review_count,
  active, vetted, created_at, updated_at
) on public.funeral_homes to anon;

grant select (
  id, name, email, phone, address, city, state, zip,
  lat, lng, google_rating, google_review_count,
  active, vetted, created_at, updated_at
) on public.funeral_homes to authenticated;

-- Re-assert the row policy (idempotent). Still no insert/update/delete policy
-- → those commands are denied for anon + authenticated; service role bypasses.
alter table public.funeral_homes enable row level security;
drop policy if exists "funeral_homes_public_read" on public.funeral_homes;
create policy "funeral_homes_public_read" on public.funeral_homes
  for select using (active = true);

-- ---------------------------------------------------------------------------
-- 2. negotiation_messages: confirm deny-by-default for update/delete
-- ---------------------------------------------------------------------------
-- The owner read + owner-send (insert) policies live in
-- 2026-05-21-coordinator-messages.sql. We intentionally add no update/delete
-- policy: the thread is an audit log. Re-assert RLS is on (idempotent).
alter table public.negotiation_messages enable row level security;


-- ==============================================================================
-- migrations/2026-06-09b-share-links-column-grant.sql
-- ==============================================================================

-- share_links: restrict anon/authenticated UPDATE to opened_at only.
-- Idempotent; safe to re-run.
--
-- The "anyone can update opened_at" RLS policy gates on expiry, but RLS is
-- row-level — it can't limit WHICH columns an UPDATE writes. So a holder of the
-- (unguessable) share UUID could overwrite the `payload` of a non-expired link,
-- not just stamp opened_at. Column-level privileges close that: drop the
-- table-wide UPDATE grant and re-grant UPDATE on opened_at alone.
--
-- Reads + inserts are unchanged; the service role bypasses these grants.

revoke update on public.share_links from anon;
revoke update on public.share_links from authenticated;

grant update (opened_at) on public.share_links to anon;
grant update (opened_at) on public.share_links to authenticated;

-- The existing RLS update policy (expiry-gated) still applies on top of this.
alter table public.share_links enable row level security;


-- ==============================================================================
-- migrations/2026-06-22-negotiation-outcomes.sql
-- ==============================================================================

-- Negotiation outcomes instrumentation: capture what actually happened, per
-- case and per home, so we can measure savings, choices, and satisfaction.
-- Run this once in the Supabase SQL editor. Idempotent.
--
-- Why: today the schema records the INBOUND side — the family's original quote
-- (negotiations.target_home_estimate_cents) and each home's quote
-- (negotiation_outreach.quote_cents) — but nothing about the OUTCOME: which
-- home was chosen, what was negotiated, what the family ultimately paid, what
-- hidden fees surfaced, and how satisfied they were. This adds those columns.
--
-- Reuse, not duplication — these already exist and are kept as-is:
--   listed_price (per case)  = negotiations.target_home_estimate_cents
--   quoted_price (per home)  = negotiation_outreach.quote_cents
--   best-quote rollup        = negotiations.best_quote_cents
-- Only genuinely-missing outcome fields are added below.
--
-- Privacy: every new column sits on a row already protected by the existing
-- owner-scoped RLS (negotiations_owner / outreach_owner, keyed on auth.uid()).
-- No policy is loosened — outcome data stays private to the owning family. The
-- internal admin view reads via the service-role key (like /admin/vetting).
--
-- The product is free to families (no advocate fee). amount_paid_cents below is
-- the price the family paid the FUNERAL HOME — an analytics figure only.

-- ---------------------------------------------------------------------------
-- Per-home outcomes (negotiation_outreach)
-- ---------------------------------------------------------------------------
alter table public.negotiation_outreach
  add column if not exists chosen boolean not null default false;

alter table public.negotiation_outreach
  add column if not exists listed_price_cents int;      -- this home's pre-negotiation list / sticker price

alter table public.negotiation_outreach
  add column if not exists negotiated_price_cents int;  -- price after we pushed back, for this home

alter table public.negotiation_outreach
  add column if not exists hidden_fees jsonb;           -- [{ "label": "...", "cents": 12345, "note": "..." }]

comment on column public.negotiation_outreach.chosen is
  'True for the single home the family selected. Set via /admin/outcomes (the founder runs pilot cases by hand); choosing a home in the product is free via /api/negotiate/choose.';
comment on column public.negotiation_outreach.hidden_fees is
  'Fees found beyond the quote. Shape: [{label, cents, note?}].';

create index if not exists outreach_chosen_idx
  on public.negotiation_outreach (negotiation_id, chosen);

-- At most one chosen home per case, enforced at the database level. The admin
-- API also clears siblings when marking a new choice (it sets the others false
-- before setting the new one true, so this partial unique index is satisfied).
create unique index if not exists negotiation_outreach_one_chosen_idx
  on public.negotiation_outreach (negotiation_id) where chosen;

-- ---------------------------------------------------------------------------
-- Per-case outcomes (negotiations)
-- ---------------------------------------------------------------------------
alter table public.negotiations
  add column if not exists negotiated_price_cents int;  -- final negotiated price on the chosen home

alter table public.negotiations
  add column if not exists amount_paid_cents int;       -- what the family paid the FUNERAL HOME (NOT the $199 fee)

alter table public.negotiations
  add column if not exists satisfaction_score smallint
  check (satisfaction_score is null or satisfaction_score between 1 and 5);

alter table public.negotiations
  add column if not exists outcome_recorded_at timestamptz;

-- Computed savings vs the family's original listed quote. Uses the amount
-- actually paid when known, else the negotiated price. NULL until both a listed
-- price and an outcome exist. (First generated column in the schema — chosen so
-- the figure can never drift from its inputs. amount_paid_cents and
-- negotiated_price_cents are added above so they exist when this is evaluated.)
alter table public.negotiations
  add column if not exists savings_vs_listed_cents int
  generated always as (
    target_home_estimate_cents - coalesce(amount_paid_cents, negotiated_price_cents)
  ) stored;

comment on column public.negotiations.amount_paid_cents is
  'Analytics only: cents the family paid the funeral home. The product is free to families — there is no advocate fee.';
comment on column public.negotiations.savings_vs_listed_cents is
  'Generated: target_home_estimate_cents - coalesce(amount_paid_cents, negotiated_price_cents).';

create index if not exists negotiations_outcome_idx
  on public.negotiations (outcome_recorded_at desc) where outcome_recorded_at is not null;

-- RLS is intentionally UNCHANGED. The new columns are covered by the existing
-- owner-scoped policies (negotiations_owner, outreach_owner). No public read is
-- added here — outcome data is family-private; the admin view uses service role.


-- ==============================================================================
-- migrations/2026-06-27-partners.sql
-- ==============================================================================

-- L3 Partner Layer — pilot #1. Idempotent, RLS-safe, employer-ready naming.
-- Run once in the Supabase SQL editor, AFTER (or alongside) the still-unapplied
-- outcomes migration (2026-06-22-negotiation-outcomes.sql). gen_random_uuid /
-- gen_random_bytes are available on modern Supabase (pgcrypto).
--
-- Design + rationale: docs/P3_PARTNER_LAYER.md (judge-panel decision, 2026-06-27).

-- 1) Tenant table. partner_type reserves the employer/insurer end-state so the
--    later employer build is ADDITIVE, never a repaint.
create table if not exists public.partners (
  id            uuid primary key default gen_random_uuid(),
  name          text not null,                       -- e.g. 'Canyon Home Hospice' (shown on the report)
  partner_type  text not null default 'hospice'
                  check (partner_type in ('hospice', 'employer', 'insurer')),
  status        text not null default 'pilot'
                  check (status in ('pilot', 'active', 'paused', 'archived')),
  -- High-entropy capability token. Possession == authorization for the
  -- read-only aggregate report. Rotate this column to revoke a shared link.
  report_token  text not null unique default encode(gen_random_bytes(24), 'hex'),
  active        boolean not null default true,
  created_at    timestamptz not null default now()
);

create index if not exists partners_report_token_idx on public.partners (report_token);

-- RLS ON, NO policies => deny-all to anon/authenticated. Only the service-role
-- key reads it (admin tooling + the report page), exactly like /admin/outcomes
-- and /admin/vetting.
alter table public.partners enable row level security;

-- 2) Attribution: tag a case to a referring partner. Nullable; most cases have
--    none. ON DELETE SET NULL so removing a partner never destroys a family's
--    case row.
alter table public.negotiations
  add column if not exists partner_id uuid references public.partners(id) on delete set null;

create index if not exists negotiations_partner_idx
  on public.negotiations (partner_id) where partner_id is not null;

comment on column public.negotiations.partner_id is
  'Referring partner (hospice). Set by the founder in /admin/outcomes AFTER the family has chosen a home. A reporting label ONLY — never read by /api/negotiate/choose, outreach, or home ranking (anti-steering is structural).';

-- negotiations / price_list_analyses RLS is INTENTIONALLY UNCHANGED. The new
-- column rides the existing owner-scoped policies; the partner report reads via
-- the service-role key with an explicit .eq('partner_id', id) filter. No anon or
-- public read is added anywhere.
--
-- DEFERRED (all additive later, FK onto partners(id) — zero repaint):
--   partner_codes(code text primary key, partner_id uuid, label text)   -- N referral codes/tenant + ?ref= cookie attribution (wave 2)
--   partner_members(partner_id uuid, email text, role text)             -- seats + magic-link / SSO for employers
--   partners.brand_logo_url / brand_color                               -- per-tenant branding
--   billing columns                                                     -- contracting


-- ==============================================================================
-- migrations/2026-07-01-bereavement-cadence.sql
-- ==============================================================================

-- Bereavement check-in cadence: re-anchor from the decommissioned paid_at to a
-- real date_of_death. Run once in the Supabase SQL editor. Idempotent.
--
-- Why: the anniversary cron (app/api/cron/anniversary) selected candidates by
-- profiles.paid_at — a column nothing writes since the family charge was
-- decommissioned — so the bereavement touchpoint engine matched zero users and
-- sent nothing. Milestones now anchor on the date of the death itself, which
-- is also the clock Medicare's hospice bereavement requirement runs on
-- (42 CFR 418.64 — support offered for up to ~13 months after the death).
--
-- The date is set ONLY when the family explicitly provides it (optional field
-- in the /negotiate/start intake). Deliberately NO proxy fallback (signup date,
-- negotiation date): a mis-anchored condolence email — e.g. to a /plan-ahead
-- user whose person has not died — is the worst possible failure mode, so no
-- date means no cadence. Under-claiming, as everywhere else in this product.
--
-- Privacy: rides the existing owner-scoped profiles RLS (profiles_self_read /
-- profiles_self_write). The cron reads via the service-role key. No policy is
-- loosened.

alter table public.profiles
  add column if not exists date_of_death date;

comment on column public.profiles.date_of_death is
  'Date of the loved one''s passing, provided explicitly by the family (optional intake field). Anchors the 1mo/3mo/6mo/1yr/13mo bereavement check-in cadence. Never inferred from signup or activity — no date, no cadence.';

-- The cron's candidate query: opted-in profiles with a death date at least the
-- shortest milestone (30 days) in the past.
create index if not exists profiles_bereavement_idx
  on public.profiles (date_of_death, anniversary_emails_opt_in)
  where date_of_death is not null;

-- The old paid_at-based partial index (profiles_anniversary_idx) is left in
-- place — harmless, and paid_at remains a legacy read for old accounts.


-- ==============================================================================
-- migrations/2026-07-02-benchmark-zip.sql
-- ==============================================================================

-- Crowdsourced benchmark pipeline (roadmap Phase 1): region-aware aggregation
-- needs the zip the family entered alongside the parsed items. Older rows
-- (zip null) still aggregate nationally.
--
-- FOUNDER-APPLIED ONLY — run in the Supabase SQL editor, same as
-- 2026-06-22-negotiation-outcomes.sql / 2026-06-27-partners.sql /
-- 2026-07-01-bereavement-cadence.sql. The code path degrades gracefully
-- until this is applied (insert retries without the column).

alter table public.price_list_analyses
  add column if not exists zip text;

comment on column public.price_list_analyses.zip is
  'Zip entered with the analysis; drives regional benchmark aggregation. De-identified use only.';


-- ==============================================================================
-- migrations/2026-07-03-bereavement-sms.sql
-- ==============================================================================

-- SMS opt-in channel for the bereavement touchpoints (roadmap Phase 3).
-- Same content arc as the email cadence, opt-IN only, cost absorbed by
-- Honest Funeral, never the family. This population skews older — SMS
-- outperforms email here.
--
-- FOUNDER-APPLIED ONLY — run with the other pending migrations. Code
-- degrades gracefully until applied AND Twilio env vars are set AND
-- BEREAVEMENT_SMS_ENABLED=true (three independent gates).

alter table public.profiles
  add column if not exists bereavement_sms_phone text,
  add column if not exists bereavement_sms_opt_in boolean not null default false,
  add column if not exists anniversary_sms_sent text[] not null default '{}';

comment on column public.profiles.bereavement_sms_phone is
  'E.164 phone for opt-in bereavement check-in texts. Never used for anything else.';


-- ==============================================================================
-- migrations/2026-07-03-household-links.sql
-- ==============================================================================

-- Live shared household link (roadmap Phase 2). Upgrades the one-time
-- /resume snapshot into a durable, owner-refreshable, read-only family view:
-- the point person's device re-publishes the snapshot to a stable slug;
-- relatives open /household/<id> and see the CURRENT state; the owner can
-- refresh, rotate (new slug, old one dies), or revoke.
--
-- Security model — deliberately different from share_links: RLS is enabled
-- with NO policies, so the anon/authed PostgREST surface cannot touch this
-- table at all (share_links' anon-select pattern would leak owner_secret).
-- Every read and write goes through our API routes using the service role,
-- which checks owner_secret for mutations and strips it from reads.
--
-- FOUNDER-APPLIED ONLY — run in the Supabase SQL editor with the other
-- pending migrations. Code degrades gracefully until applied (the /family
-- card reports the live link as unavailable; nothing else breaks).

create table if not exists public.household_links (
  id uuid primary key default gen_random_uuid(),
  -- Presented ONCE to the creating device and stored in its localStorage;
  -- required for update/rotate/revoke. Never returned by any read path.
  owner_secret uuid not null default gen_random_uuid(),
  payload jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- Rolling expiry: refreshed to now() + 30 days on every owner update.
  expires_at timestamptz not null default (now() + interval '30 days'),
  revoked_at timestamptz,
  -- Rotation trail: the row this one replaced (old slug is revoked).
  rotated_from uuid
);

create index if not exists household_links_expiry_idx
  on public.household_links (expires_at);

alter table public.household_links enable row level security;
-- No policies on purpose: service-role access only.

comment on table public.household_links is
  'Durable read-only family view slugs. Service-role only; owner_secret gates mutations. See app/api/household/*.';


-- ==============================================================================
-- migrations/2026-07-03-partner-codes.sql
-- ==============================================================================

-- Self-serve neutral referral codes (roadmap Phase 4, item 1).
--
-- A hospice coordinator — holding the partner's founder-issued report_token —
-- generates their own referral links at /partner/r/<token>/links, no engineer
-- involved. A family arriving through ?ref=<code> is attributed to the
-- institution when (and only when) they start a negotiation, for AGGREGATE
-- reporting only. Invariants preserved by construction:
--   * partner_id/partner_code are reporting labels — never read by
--     /api/negotiate/choose, outreach, or any home-selection logic.
--   * The coordinator surface shows per-code claim COUNTS only; no case
--     detail, no home names, no prices (zero-visibility rule).
--   * Founder approval stays upstream: codes can only hang off a partners
--     row, and partners rows are founder-created.
--
-- FOUNDER-APPLIED ONLY — run with the other pending migrations (requires
-- 2026-06-27-partners.sql first). Code degrades gracefully until applied.

create table if not exists public.partner_codes (
  code text primary key,                       -- e.g. 'HF-7KQ2MD' (unambiguous alphabet)
  partner_id uuid not null references public.partners(id) on delete cascade,
  label text,                                  -- coordinator's own note, e.g. 'front-desk QR'
  active boolean not null default true,
  created_at timestamptz not null default now(),
  revoked_at timestamptz
);

create index if not exists partner_codes_partner_idx
  on public.partner_codes (partner_id, created_at desc);

alter table public.partner_codes enable row level security;
-- No policies on purpose: service-role access only, same as partners.

-- The code a negotiation was claimed under (partner_id is derived from it at
-- claim time and stays authoritative for reporting).
alter table public.negotiations
  add column if not exists partner_code text references public.partner_codes(code) on delete set null;

comment on table public.partner_codes is
  'Coordinator-generated referral codes. Reporting attribution only — never read by selection/outreach logic.';


-- ==============================================================================
-- migrations/2026-07-03-partner-onboarding.sql
-- ==============================================================================

-- Self-serve hospice partner onboarding (roadmap Phase 4): the application
-- form writes a PENDING partners row (active=false — inert everywhere: the
-- report page, the links manager, and code resolution all require active).
-- A human — the founder — flips active on /admin/partners. Every new
-- institutional money relationship keeps its human approval gate.
--
-- FOUNDER-APPLIED ONLY — run with the other pending migrations (requires
-- 2026-06-27-partners.sql).

alter table public.partners
  add column if not exists contact_name text,
  add column if not exists contact_email text,
  add column if not exists application_notes text,
  add column if not exists approved_at timestamptz;

comment on column public.partners.approved_at is
  'Set when the founder activates the partner on /admin/partners. active=false rows are pending applications.';


-- ==============================================================================
-- migrations/2026-07-03-pilot-metrics.sql
-- ==============================================================================

-- The five pilot metrics (roadmap Phase 4): benefit dollars recovered is the
-- one metric with no existing column — admin-entered per case during the
-- pilot (VA burial benefits, SSA lump sum, located life policies, county
-- assistance actually claimed). Aggregate-only on every partner surface.
--
-- FOUNDER-APPLIED ONLY — run with the other pending migrations.

alter table public.negotiations
  add column if not exists benefit_dollars_recovered_cents int;

comment on column public.negotiations.benefit_dollars_recovered_cents is
  'Admin-entered during the pilot: benefit dollars the family actually recovered (VA/SSA/insurance/county). Reporting aggregate only.';


-- ==============================================================================
-- migrations/2026-07-13-portal-identity.sql
-- ==============================================================================

-- Portal identity (product week Day 1): partner sign-in seats, captured demo
-- leads, analyzer attribution + extraction provenance, and the AI cost ledger.
--
-- partner_members is the table 2026-06-27-partners.sql explicitly reserved:
-- who may SIGN IN to /portal for a partner org. Additive on the
-- partners/partner_codes token model — report_token quick links keep working
-- unchanged; a seat just adds a session-gated way in (lib/partner/auth.ts
-- mirrors the admin gate). invited_email is stored LOWERCASE at every write
-- site; a member binds to their auth.users row on first login by email match.
--
-- FOUNDER-APPLIED ONLY — run in the Supabase SQL editor, same as the other
-- 2026-06/07 migrations. Idempotent. Requires 2026-06-27-partners.sql and
-- 2026-07-03-partner-codes.sql.

create table if not exists public.partner_members (
  id             uuid primary key default gen_random_uuid(),
  partner_id     uuid not null references public.partners(id) on delete cascade,
  invited_email  text not null,
  role           text not null default 'member' check (role in ('owner', 'member')),
  user_id        uuid references auth.users(id) on delete set null,
  invited_at     timestamptz not null default now(),
  accepted_at    timestamptz,
  deactivated_at timestamptz,
  created_at     timestamptz not null default now()
);

comment on table public.partner_members is
  'Sign-in seats for /portal. RLS deny-all: reads/writes go through the service role behind lib/partner/auth.ts (requirePartnerMember), same posture as partners/partner_codes.';
comment on column public.partner_members.invited_email is
  'Always stored lowercase. Binds to auth.users on first login by email match (user_id + accepted_at stamped then).';
comment on column public.partner_members.deactivated_at is
  'Soft removal — a deactivated seat can no longer enter /portal but keeps its history.';

-- RLS: enabled, ZERO policies (deny-all; service-role only).
alter table public.partner_members enable row level security;

-- Plain-column unique index (not functional) so ON CONFLICT upserts can
-- target it; invited_email is lowercased at every write site instead.
create unique index if not exists partner_members_partner_email_idx
  on public.partner_members (partner_id, invited_email);
create index if not exists partner_members_user_idx
  on public.partner_members (user_id) where user_id is not null;

-- ---------------------------------------------------------------------------
-- partner_leads: "schedule a call" demo requests currently email the founder
-- and vanish (no row anywhere). Insert-only via service role from
-- /api/partner/demo-request; surfaced read-only on /admin/partners.

create table if not exists public.partner_leads (
  id         uuid primary key default gen_random_uuid(),
  name       text,
  org        text,
  email      text not null,
  note       text,
  source     text not null default 'demo-request',
  handled_at timestamptz,
  created_at timestamptz not null default now()
);

comment on table public.partner_leads is
  'Institutional demo/contact requests. RLS deny-all (service-role only); admin reads via the session gate.';

alter table public.partner_leads enable row level security;

-- ---------------------------------------------------------------------------
-- Portal settings columns (Day 2 UI; columns land with the identity migration
-- so the week needs no partners-table follow-up).

alter table public.partners
  add column if not exists brand_accent text,
  add column if not exists notification_email text;

comment on column public.partners.brand_accent is
  'Optional co-brand accent (hex). Name + accent only — no logo upload this cycle.';
comment on column public.partners.notification_email is
  'Where the monthly digest goes. Falls back to contact_email when null.';

-- ---------------------------------------------------------------------------
-- Analyzer attribution + extraction provenance. partner_id/partner_code are
-- reporting labels ONLY — never read by home selection, outreach, or ranking
-- (anti-steering is structural, same contract as negotiations.partner_id).
-- Written best-effort by the service role after the family's own insert; the
-- family flow never fails over attribution.

alter table public.price_list_analyses
  add column if not exists partner_id uuid references public.partners(id) on delete set null,
  add column if not exists partner_code text references public.partner_codes(code) on delete set null,
  add column if not exists confidence numeric,
  add column if not exists extraction_method text;

comment on column public.price_list_analyses.partner_id is
  'Reporting attribution only (referred family ran the checker). Never an input to any recommendation.';
comment on column public.price_list_analyses.extraction_method is
  'How the items were parsed: claude | naive | founder_ingest.';
comment on column public.price_list_analyses.confidence is
  '0-1 extraction confidence (item count + total consistency heuristic).';

create index if not exists price_list_analyses_partner_idx
  on public.price_list_analyses (partner_id) where partner_id is not null;

-- ---------------------------------------------------------------------------
-- api_cost_events: per-call AI cost ledger (AI_STRATEGY §3.3 #1). Written
-- best-effort by lib/claude.ts recordUsage(); a logging failure never blocks
-- a user-facing call.

create table if not exists public.api_cost_events (
  id               uuid primary key default gen_random_uuid(),
  feature          text not null,
  model            text not null,
  input_tokens     int not null default 0,
  output_tokens    int not null default 0,
  cache_read_tokens int not null default 0,
  negotiation_id   uuid,
  created_at       timestamptz not null default now()
);

comment on table public.api_cost_events is
  'One row per Claude API call: feature tag + token usage. RLS deny-all (service-role only).';

alter table public.api_cost_events enable row level security;

create index if not exists api_cost_events_feature_idx
  on public.api_cost_events (feature, created_at desc);


-- ==============================================================================
-- migrations/2026-07-16-inbound-ai-parse.sql
-- ==============================================================================

-- Inbound AI parse (product week Day 4): a funeral home's email reply is
-- auto-parsed into a PROPOSED quote the family confirms with one click (P7).
--
-- The five ai_* columns hold the unconfirmed proposal only. They are never
-- ground truth: confirming still flows through the existing
-- /api/negotiate/[id]/quote route (the same path a hand-typed quote takes),
-- which then stamps ai_confirmed_at. Rides the existing negotiation_messages
-- RLS — owner-scoped SELECT, no family UPDATE policy, so the webhook and the
-- confirm stamp both write via the service role.
--
-- FOUNDER-APPLIED ONLY — run in the Supabase SQL editor, same as the other
-- 2026-06/07 migrations. Idempotent. Requires 2026-05-21-coordinator-messages.sql.

alter table public.negotiation_messages
  add column if not exists ai_quote_cents int,
  add column if not exists ai_quote_items jsonb,
  add column if not exists ai_parse_confidence numeric,
  add column if not exists ai_parsed_at timestamptz,
  add column if not exists ai_confirmed_at timestamptz;

comment on column public.negotiation_messages.ai_quote_cents is
  'AI-proposed all-in quote parsed from this inbound reply. A PROPOSAL only — never ground truth until a human confirms via /api/negotiate/[id]/quote.';
comment on column public.negotiation_messages.ai_quote_items is
  'AI-proposed itemization: [{name, cents}]. Same proposal-only contract as ai_quote_cents.';
comment on column public.negotiation_messages.ai_parse_confidence is
  '0-1 parse confidence (item count + stated-total consistency heuristic). Low-confidence parses are dropped, not stored.';
comment on column public.negotiation_messages.ai_parsed_at is
  'When the best-effort inbound parse ran. Null = never parsed (short body, Claude off, or parse declined).';
comment on column public.negotiation_messages.ai_confirmed_at is
  'When a human clicked "Use this" and the quote was written through the existing quote route. Null = still just a proposal.';
