import { createHmac } from "node:crypto";

/**
 * Canonical message covered by the /og URL signature. MUST stay in
 * lockstep with the recomputation in `lib/og-verify.ts` (edge-safe,
 * can't import this file because of the node:crypto dependency).
 *
 * The title is length-prefixed so the field boundary is unambiguous —
 * with a bare joiner, a signature over a newline-bearing title would
 * also verify for the re-split pair (text migrating between title and
 * eyebrow). No call site signs newlines today; the prefix keeps that
 * from ever becoming a hole.
 */
function ogSigningMessage(title: string, eyebrow?: string): string {
  return `${title.length}\n${title}\n${eyebrow ?? ""}`;
}

/**
 * Build the /og query string, signed with OG_SIGNING_SECRET when it is
 * set (audit A1-05: without a signature anyone can mint official-looking
 * cards from arbitrary query text). Unset secret → unsigned, the
 * pre-signing behavior (local dev / previews without the env).
 *
 * Synchronous on purpose: call sites include static `metadata` exports.
 */
export function ogQueryString(title: string, eyebrow?: string): string {
  const params = new URLSearchParams();
  params.set("title", title);
  if (eyebrow) params.set("eyebrow", eyebrow);
  const secret = process.env.OG_SIGNING_SECRET;
  if (secret) {
    const sig = createHmac("sha256", secret)
      .update(ogSigningMessage(title, eyebrow))
      .digest("hex");
    params.set("sig", sig);
  }
  return params.toString();
}

/**
 * Build the URL for a per-page OG image generated by /og.
 *
 * Returns just the path (e.g. `/og?title=Pet+loss&eyebrow=Grief`).
 * Next.js metadataBase prepends the canonical domain when generating
 * the actual <meta property="og:image"> tag, so callers don't need to
 * include the host.
 */
export function ogImage(
  title: string,
  eyebrow?: string,
): { url: string; width: number; height: number; alt: string } {
  return {
    url: `/og?${ogQueryString(title, eyebrow)}`,
    width: 1200,
    height: 630,
    alt: `${title} — Honest Funeral`,
  };
}
