/**
 * Build the URL for a per-page OG image generated by /og.
 *
 * Returns just the path (e.g. `/og?title=Pet+loss&eyebrow=Grief`).
 * Next.js metadataBase prepends the canonical domain when generating
 * the actual <meta property="og:image"> tag, so callers don't need to
 * include the host.
 */
export function ogImage(
  title: string,
  eyebrow?: string,
): { url: string; width: number; height: number; alt: string } {
  const params = new URLSearchParams();
  params.set("title", title);
  if (eyebrow) params.set("eyebrow", eyebrow);
  return {
    url: `/og?${params.toString()}`,
    width: 1200,
    height: 630,
    alt: `${title} — Honest Funeral`,
  };
}
