/**
 * Metro-area zip prefix lookup for regional pricing precision.
 *
 * Maps the first 3 digits of a US zip code to:
 *   - multiplier: cost-of-living adjustment vs. national average (1.00)
 *   - metro: human-readable metro/area label (e.g., "Manhattan, NY")
 *
 * This replaces the original 3-bucket multiplier (high-coastal /
 * baseline / low-COL) with ~150 metro-level entries covering most of
 * the US population. Where a zip's 3-digit prefix isn't in the table,
 * regionMultiplier() falls back to the 1-digit prefix logic below.
 *
 * Multipliers are best-fit estimates calibrated against:
 *   - BLS Regional Price Parities by metro
 *   - General cost-of-living indexes (Numbeo, BestPlaces, etc.)
 *   - Industry knowledge of funeral-pricing variation per region
 *
 * NOT validated against actual General Price Lists — these multipliers
 * power the "modeled" data tier (dataSourceForZip's static answer).
 * Regions upgrade to "verified"/"community" via regional_benchmarks
 * override rows, founder-promoted at n≥5 on /admin/benchmarks and read
 * by lib/benchmarks-store.ts (metro-scoped rows match on the exact
 * metro labels below).
 *
 * Range: 0.75 (rural Mississippi / Appalachian KY) to 1.50 (Manhattan,
 * SF, Honolulu).
 */

export interface ZipRegion {
  multiplier: number;
  metro: string;
  state: string;
}

export const ZIP_REGIONS: Record<string, ZipRegion> = {
  // -------------------------------------------------------------
  // NORTHEAST — Massachusetts, Connecticut, Rhode Island, Vermont,
  // New Hampshire, Maine
  // -------------------------------------------------------------
  "010": { multiplier: 1.05, metro: "Worcester area", state: "MA" },
  "011": { multiplier: 1.05, metro: "Worcester area", state: "MA" },
  "012": { multiplier: 1.00, metro: "Pittsfield/Springfield", state: "MA" },
  "013": { multiplier: 1.00, metro: "Springfield", state: "MA" },
  "014": { multiplier: 1.20, metro: "Boston suburbs (west)", state: "MA" },
  "015": { multiplier: 1.20, metro: "Boston suburbs (west)", state: "MA" },
  "017": { multiplier: 1.25, metro: "Greater Boston (north)", state: "MA" },
  "018": { multiplier: 1.20, metro: "Greater Boston (north)", state: "MA" },
  "019": { multiplier: 1.20, metro: "Boston North Shore", state: "MA" },
  "020": { multiplier: 1.25, metro: "Greater Boston (south)", state: "MA" },
  "021": { multiplier: 1.40, metro: "Boston", state: "MA" },
  "022": { multiplier: 1.40, metro: "Boston", state: "MA" },
  "023": { multiplier: 1.20, metro: "Brockton area", state: "MA" },
  "024": { multiplier: 1.20, metro: "Brockton area", state: "MA" },
  "025": { multiplier: 1.20, metro: "Cape Cod", state: "MA" },
  "026": { multiplier: 1.20, metro: "Cape Cod", state: "MA" },
  "027": { multiplier: 1.20, metro: "Cape Cod / New Bedford", state: "MA" },
  "028": { multiplier: 1.05, metro: "Providence area", state: "RI" },
  "029": { multiplier: 1.05, metro: "Providence", state: "RI" },
  "030": { multiplier: 1.05, metro: "New Hampshire (south)", state: "NH" },
  "031": { multiplier: 1.05, metro: "Manchester area", state: "NH" },
  "032": { multiplier: 1.00, metro: "Concord area", state: "NH" },
  "033": { multiplier: 1.00, metro: "Lakes Region", state: "NH" },
  "034": { multiplier: 0.95, metro: "Northern NH", state: "NH" },
  "035": { multiplier: 0.95, metro: "Vermont", state: "VT" },
  "036": { multiplier: 0.95, metro: "Vermont", state: "VT" },
  "037": { multiplier: 0.95, metro: "Vermont", state: "VT" },
  "038": { multiplier: 0.95, metro: "Maine (southern)", state: "ME" },
  "039": { multiplier: 0.95, metro: "Maine (southern)", state: "ME" },
  "040": { multiplier: 0.95, metro: "Portland area", state: "ME" },
  "041": { multiplier: 0.95, metro: "Portland area", state: "ME" },
  "042": { multiplier: 0.90, metro: "Maine (central)", state: "ME" },
  "043": { multiplier: 0.90, metro: "Maine", state: "ME" },
  "044": { multiplier: 0.90, metro: "Maine (Bangor)", state: "ME" },
  "045": { multiplier: 0.85, metro: "Maine (north)", state: "ME" },
  "046": { multiplier: 0.85, metro: "Maine (north)", state: "ME" },
  "047": { multiplier: 0.85, metro: "Maine (north)", state: "ME" },
  "048": { multiplier: 0.85, metro: "Maine (north)", state: "ME" },
  "049": { multiplier: 0.85, metro: "Maine (north)", state: "ME" },

  // -------------------------------------------------------------
  // NEW YORK / NEW JERSEY
  // -------------------------------------------------------------
  "060": { multiplier: 1.10, metro: "Hartford area", state: "CT" },
  "061": { multiplier: 1.05, metro: "Hartford", state: "CT" },
  "062": { multiplier: 1.00, metro: "Connecticut (NE)", state: "CT" },
  "063": { multiplier: 1.00, metro: "Connecticut (E)", state: "CT" },
  "064": { multiplier: 1.10, metro: "New Haven", state: "CT" },
  "065": { multiplier: 1.10, metro: "New Haven area", state: "CT" },
  "066": { multiplier: 1.20, metro: "Stamford/Greenwich", state: "CT" },
  "067": { multiplier: 1.15, metro: "Bridgeport area", state: "CT" },
  "068": { multiplier: 1.20, metro: "Stamford area", state: "CT" },
  "069": { multiplier: 1.15, metro: "Connecticut (SW)", state: "CT" },
  "070": { multiplier: 1.30, metro: "Newark/Jersey City", state: "NJ" },
  "071": { multiplier: 1.30, metro: "Newark/Paterson", state: "NJ" },
  "072": { multiplier: 1.25, metro: "Northern NJ", state: "NJ" },
  "073": { multiplier: 1.30, metro: "Jersey City/Hudson", state: "NJ" },
  "074": { multiplier: 1.25, metro: "Northern NJ", state: "NJ" },
  "075": { multiplier: 1.25, metro: "Northern NJ", state: "NJ" },
  "076": { multiplier: 1.20, metro: "Hackensack area", state: "NJ" },
  "077": { multiplier: 1.20, metro: "Northern NJ", state: "NJ" },
  "078": { multiplier: 1.10, metro: "Trenton area", state: "NJ" },
  "079": { multiplier: 1.05, metro: "Trenton area", state: "NJ" },
  "080": { multiplier: 1.05, metro: "South Jersey", state: "NJ" },
  "081": { multiplier: 1.00, metro: "Camden area", state: "NJ" },
  "082": { multiplier: 1.00, metro: "South Jersey", state: "NJ" },
  "083": { multiplier: 1.05, metro: "South Jersey", state: "NJ" },
  "084": { multiplier: 1.05, metro: "Atlantic City area", state: "NJ" },
  "085": { multiplier: 1.05, metro: "Trenton/Princeton", state: "NJ" },
  "086": { multiplier: 1.10, metro: "Princeton area", state: "NJ" },
  "087": { multiplier: 1.05, metro: "Central NJ", state: "NJ" },
  "088": { multiplier: 1.05, metro: "Central NJ shore", state: "NJ" },
  "089": { multiplier: 1.05, metro: "Central NJ", state: "NJ" },
  "100": { multiplier: 1.50, metro: "Manhattan", state: "NY" },
  "101": { multiplier: 1.50, metro: "Manhattan", state: "NY" },
  "102": { multiplier: 1.45, metro: "Manhattan", state: "NY" },
  "103": { multiplier: 1.30, metro: "Staten Island", state: "NY" },
  "104": { multiplier: 1.30, metro: "The Bronx", state: "NY" },
  "105": { multiplier: 1.30, metro: "Westchester (south)", state: "NY" },
  "106": { multiplier: 1.30, metro: "Yonkers/Westchester", state: "NY" },
  "107": { multiplier: 1.30, metro: "Westchester", state: "NY" },
  "108": { multiplier: 1.25, metro: "Westchester (north)", state: "NY" },
  "109": { multiplier: 1.20, metro: "Hudson Valley", state: "NY" },
  "110": { multiplier: 1.30, metro: "Queens", state: "NY" },
  "111": { multiplier: 1.30, metro: "Queens", state: "NY" },
  "112": { multiplier: 1.30, metro: "Brooklyn", state: "NY" },
  "113": { multiplier: 1.30, metro: "Queens", state: "NY" },
  "114": { multiplier: 1.30, metro: "Queens", state: "NY" },
  "115": { multiplier: 1.20, metro: "Long Island (Nassau)", state: "NY" },
  "116": { multiplier: 1.25, metro: "Far Rockaway / SE Queens", state: "NY" },
  "117": { multiplier: 1.20, metro: "Long Island (Nassau)", state: "NY" },
  "118": { multiplier: 1.20, metro: "Long Island (Suffolk)", state: "NY" },
  "119": { multiplier: 1.20, metro: "Long Island (Suffolk)", state: "NY" },
  "120": { multiplier: 0.95, metro: "Albany area", state: "NY" },
  "121": { multiplier: 0.95, metro: "Albany area", state: "NY" },
  "122": { multiplier: 0.95, metro: "Albany", state: "NY" },
  "123": { multiplier: 0.90, metro: "Schenectady", state: "NY" },
  "124": { multiplier: 0.90, metro: "Hudson Valley (north)", state: "NY" },
  "125": { multiplier: 1.00, metro: "Poughkeepsie", state: "NY" },
  "126": { multiplier: 0.95, metro: "Hudson Valley", state: "NY" },
  "127": { multiplier: 0.90, metro: "Binghamton", state: "NY" },
  "128": { multiplier: 0.90, metro: "Adirondacks", state: "NY" },
  "129": { multiplier: 0.85, metro: "Adirondacks", state: "NY" },
  "130": { multiplier: 0.90, metro: "Syracuse", state: "NY" },
  "131": { multiplier: 0.90, metro: "Syracuse", state: "NY" },
  "132": { multiplier: 0.90, metro: "Syracuse", state: "NY" },
  "133": { multiplier: 0.90, metro: "Utica", state: "NY" },
  "134": { multiplier: 0.85, metro: "Watertown", state: "NY" },
  "135": { multiplier: 0.85, metro: "Central NY", state: "NY" },
  "136": { multiplier: 0.85, metro: "Central NY", state: "NY" },
  "137": { multiplier: 0.85, metro: "Ithaca area", state: "NY" },
  "138": { multiplier: 0.85, metro: "Elmira area", state: "NY" },
  "139": { multiplier: 0.85, metro: "Western NY", state: "NY" },
  "140": { multiplier: 0.85, metro: "Buffalo", state: "NY" },
  "141": { multiplier: 0.85, metro: "Buffalo area", state: "NY" },
  "142": { multiplier: 0.85, metro: "Buffalo", state: "NY" },
  "143": { multiplier: 0.85, metro: "Niagara Falls", state: "NY" },
  "144": { multiplier: 0.90, metro: "Rochester", state: "NY" },
  "145": { multiplier: 0.90, metro: "Rochester area", state: "NY" },
  "146": { multiplier: 0.90, metro: "Rochester", state: "NY" },
  "147": { multiplier: 0.85, metro: "Western NY", state: "NY" },
  "148": { multiplier: 0.85, metro: "Western NY", state: "NY" },
  "149": { multiplier: 0.85, metro: "Western NY", state: "NY" },

  // -------------------------------------------------------------
  // PENNSYLVANIA
  // -------------------------------------------------------------
  "150": { multiplier: 0.85, metro: "Pittsburgh area", state: "PA" },
  "151": { multiplier: 0.85, metro: "Pittsburgh area", state: "PA" },
  "152": { multiplier: 0.90, metro: "Pittsburgh", state: "PA" },
  "153": { multiplier: 0.85, metro: "Pittsburgh", state: "PA" },
  "154": { multiplier: 0.85, metro: "Western PA", state: "PA" },
  "155": { multiplier: 0.85, metro: "Western PA", state: "PA" },
  "156": { multiplier: 0.85, metro: "Western PA", state: "PA" },
  "157": { multiplier: 0.80, metro: "Western PA", state: "PA" },
  "158": { multiplier: 0.80, metro: "Western PA", state: "PA" },
  "159": { multiplier: 0.80, metro: "Western PA", state: "PA" },
  "160": { multiplier: 0.80, metro: "Western PA", state: "PA" },
  "161": { multiplier: 0.80, metro: "Erie area", state: "PA" },
  "162": { multiplier: 0.85, metro: "Erie", state: "PA" },
  "163": { multiplier: 0.85, metro: "Erie", state: "PA" },
  "164": { multiplier: 0.85, metro: "Erie/NW PA", state: "PA" },
  "165": { multiplier: 0.85, metro: "NW Pennsylvania", state: "PA" },
  "166": { multiplier: 0.80, metro: "Central PA", state: "PA" },
  "167": { multiplier: 0.80, metro: "Central PA", state: "PA" },
  "168": { multiplier: 0.80, metro: "Central PA", state: "PA" },
  "169": { multiplier: 0.80, metro: "Williamsport", state: "PA" },
  "170": { multiplier: 0.85, metro: "Harrisburg", state: "PA" },
  "171": { multiplier: 0.85, metro: "Harrisburg", state: "PA" },
  "172": { multiplier: 0.85, metro: "Harrisburg", state: "PA" },
  "173": { multiplier: 0.85, metro: "Lancaster area", state: "PA" },
  "174": { multiplier: 0.85, metro: "York", state: "PA" },
  "175": { multiplier: 0.85, metro: "Lancaster", state: "PA" },
  "176": { multiplier: 0.85, metro: "Lancaster area", state: "PA" },
  "177": { multiplier: 0.85, metro: "Williamsport/N central PA", state: "PA" },
  "178": { multiplier: 0.85, metro: "Central PA", state: "PA" },
  "179": { multiplier: 0.85, metro: "Reading area", state: "PA" },
  "180": { multiplier: 0.95, metro: "Allentown/Bethlehem", state: "PA" },
  "181": { multiplier: 0.90, metro: "Allentown area", state: "PA" },
  "182": { multiplier: 0.90, metro: "Wilkes-Barre area", state: "PA" },
  "183": { multiplier: 0.85, metro: "Lehigh Valley", state: "PA" },
  "184": { multiplier: 0.85, metro: "Scranton", state: "PA" },
  "185": { multiplier: 0.85, metro: "Scranton", state: "PA" },
  "186": { multiplier: 0.85, metro: "NE Pennsylvania", state: "PA" },
  "187": { multiplier: 0.85, metro: "NE Pennsylvania", state: "PA" },
  "188": { multiplier: 0.85, metro: "NE Pennsylvania", state: "PA" },
  "189": { multiplier: 0.95, metro: "Philadelphia suburbs", state: "PA" },
  "190": { multiplier: 1.05, metro: "Philadelphia (W)", state: "PA" },
  "191": { multiplier: 1.05, metro: "Philadelphia", state: "PA" },
  "192": { multiplier: 1.05, metro: "Philadelphia", state: "PA" },
  "193": { multiplier: 1.05, metro: "Philadelphia (NW)", state: "PA" },
  "194": { multiplier: 1.00, metro: "Philadelphia suburbs", state: "PA" },
  "195": { multiplier: 1.00, metro: "Philadelphia (Reading)", state: "PA" },
  "196": { multiplier: 0.95, metro: "Reading", state: "PA" },

  // -------------------------------------------------------------
  // DC / MARYLAND / VIRGINIA / DELAWARE
  // -------------------------------------------------------------
  "197": { multiplier: 1.00, metro: "Wilmington, DE", state: "DE" },
  "198": { multiplier: 0.95, metro: "Delaware", state: "DE" },
  "199": { multiplier: 0.90, metro: "Delaware (south)", state: "DE" },
  "200": { multiplier: 1.20, metro: "Washington DC", state: "DC" },
  "201": { multiplier: 1.15, metro: "DC suburbs (VA)", state: "VA" },
  "202": { multiplier: 1.20, metro: "Washington DC", state: "DC" },
  "203": { multiplier: 1.20, metro: "Washington DC", state: "DC" },
  "204": { multiplier: 1.20, metro: "Washington DC", state: "DC" },
  "205": { multiplier: 1.20, metro: "Washington DC", state: "DC" },
  "206": { multiplier: 1.15, metro: "DC suburbs (MD)", state: "MD" },
  "207": { multiplier: 1.15, metro: "Bethesda/Silver Spring", state: "MD" },
  "208": { multiplier: 1.15, metro: "Montgomery County", state: "MD" },
  "209": { multiplier: 1.15, metro: "Bethesda area", state: "MD" },
  "210": { multiplier: 1.00, metro: "Baltimore (W)", state: "MD" },
  "211": { multiplier: 1.00, metro: "Baltimore", state: "MD" },
  "212": { multiplier: 1.00, metro: "Baltimore", state: "MD" },
  "213": { multiplier: 0.95, metro: "Maryland (W)", state: "MD" },
  "214": { multiplier: 0.95, metro: "Annapolis area", state: "MD" },
  "215": { multiplier: 0.90, metro: "Maryland (W)", state: "MD" },
  "216": { multiplier: 0.90, metro: "Eastern Shore MD", state: "MD" },
  "217": { multiplier: 0.85, metro: "Eastern Shore MD", state: "MD" },
  "218": { multiplier: 0.85, metro: "Eastern Shore MD", state: "MD" },
  "219": { multiplier: 0.95, metro: "Annapolis area", state: "MD" },
  "220": { multiplier: 1.15, metro: "Northern VA (Arlington)", state: "VA" },
  "221": { multiplier: 1.15, metro: "Alexandria/Fairfax", state: "VA" },
  "222": { multiplier: 1.15, metro: "Northern VA", state: "VA" },
  "223": { multiplier: 1.05, metro: "Northern VA", state: "VA" },
  "224": { multiplier: 0.95, metro: "Fredericksburg", state: "VA" },
  "225": { multiplier: 0.95, metro: "Northern VA (rural)", state: "VA" },
  "226": { multiplier: 0.90, metro: "Shenandoah Valley", state: "VA" },
  "227": { multiplier: 0.90, metro: "Charlottesville area", state: "VA" },
  "228": { multiplier: 0.90, metro: "Roanoke area", state: "VA" },
  "229": { multiplier: 0.95, metro: "Charlottesville", state: "VA" },
  "230": { multiplier: 0.90, metro: "Richmond (W)", state: "VA" },
  "231": { multiplier: 0.90, metro: "Richmond area", state: "VA" },
  "232": { multiplier: 0.90, metro: "Richmond", state: "VA" },
  "233": { multiplier: 0.95, metro: "Norfolk/Virginia Beach", state: "VA" },
  "234": { multiplier: 0.95, metro: "Virginia Beach", state: "VA" },
  "235": { multiplier: 0.90, metro: "Newport News", state: "VA" },
  "236": { multiplier: 0.90, metro: "Hampton Roads", state: "VA" },
  "237": { multiplier: 0.90, metro: "Hampton Roads", state: "VA" },
  "238": { multiplier: 0.90, metro: "Eastern VA", state: "VA" },
  "239": { multiplier: 0.85, metro: "Lynchburg area", state: "VA" },
  "240": { multiplier: 0.85, metro: "Roanoke", state: "VA" },
  "241": { multiplier: 0.85, metro: "Roanoke area", state: "VA" },
  "242": { multiplier: 0.85, metro: "SW Virginia", state: "VA" },
  "243": { multiplier: 0.85, metro: "SW Virginia", state: "VA" },
  "244": { multiplier: 0.80, metro: "SW Virginia", state: "VA" },
  "245": { multiplier: 0.80, metro: "SW Virginia", state: "VA" },
  "246": { multiplier: 0.80, metro: "SW Virginia", state: "VA" },
  "247": { multiplier: 0.80, metro: "Western WV", state: "WV" },
  "248": { multiplier: 0.80, metro: "Bluefield area", state: "WV" },
  "249": { multiplier: 0.80, metro: "Beckley", state: "WV" },
  "250": { multiplier: 0.85, metro: "Charleston, WV", state: "WV" },
  "251": { multiplier: 0.85, metro: "Charleston, WV", state: "WV" },
  "252": { multiplier: 0.80, metro: "WV (south)", state: "WV" },
  "253": { multiplier: 0.80, metro: "WV (south)", state: "WV" },
  "254": { multiplier: 0.80, metro: "WV (south)", state: "WV" },
  "255": { multiplier: 0.80, metro: "Huntington, WV", state: "WV" },
  "256": { multiplier: 0.80, metro: "Huntington area", state: "WV" },
  "257": { multiplier: 0.80, metro: "WV", state: "WV" },
  "258": { multiplier: 0.80, metro: "WV", state: "WV" },
  "259": { multiplier: 0.80, metro: "WV", state: "WV" },
  "260": { multiplier: 0.80, metro: "Wheeling area", state: "WV" },
  "261": { multiplier: 0.80, metro: "WV (north)", state: "WV" },
  "262": { multiplier: 0.80, metro: "Morgantown, WV", state: "WV" },
  "263": { multiplier: 0.80, metro: "WV", state: "WV" },
  "264": { multiplier: 0.80, metro: "WV", state: "WV" },
  "265": { multiplier: 0.80, metro: "Wheeling", state: "WV" },
  "266": { multiplier: 0.80, metro: "WV", state: "WV" },
  "267": { multiplier: 0.80, metro: "WV (E)", state: "WV" },
  "268": { multiplier: 0.85, metro: "Martinsburg, WV", state: "WV" },

  // -------------------------------------------------------------
  // SOUTHEAST — North Carolina, South Carolina, Georgia, Florida,
  // Alabama, Mississippi, Tennessee, Kentucky, Louisiana
  // -------------------------------------------------------------
  "270": { multiplier: 0.85, metro: "Greensboro area", state: "NC" },
  "271": { multiplier: 0.90, metro: "Winston-Salem", state: "NC" },
  "272": { multiplier: 0.95, metro: "Greensboro", state: "NC" },
  "273": { multiplier: 0.90, metro: "Greensboro area", state: "NC" },
  "274": { multiplier: 0.85, metro: "NC (W)", state: "NC" },
  "275": { multiplier: 1.00, metro: "Raleigh", state: "NC" },
  "276": { multiplier: 1.00, metro: "Durham", state: "NC" },
  "277": { multiplier: 1.00, metro: "Raleigh-Durham", state: "NC" },
  "278": { multiplier: 0.85, metro: "Eastern NC", state: "NC" },
  "279": { multiplier: 0.85, metro: "Eastern NC", state: "NC" },
  "280": { multiplier: 0.95, metro: "Charlotte", state: "NC" },
  "281": { multiplier: 0.95, metro: "Charlotte", state: "NC" },
  "282": { multiplier: 0.95, metro: "Charlotte", state: "NC" },
  "283": { multiplier: 0.85, metro: "NC (south)", state: "NC" },
  "284": { multiplier: 0.85, metro: "NC", state: "NC" },
  "285": { multiplier: 0.85, metro: "NC", state: "NC" },
  "286": { multiplier: 0.85, metro: "NC (W)", state: "NC" },
  "287": { multiplier: 0.90, metro: "Asheville", state: "NC" },
  "288": { multiplier: 0.85, metro: "NC mountains", state: "NC" },
  "289": { multiplier: 0.85, metro: "NC (W)", state: "NC" },
  "290": { multiplier: 0.90, metro: "Columbia", state: "SC" },
  "291": { multiplier: 0.85, metro: "South Carolina", state: "SC" },
  "292": { multiplier: 0.90, metro: "Columbia, SC", state: "SC" },
  "293": { multiplier: 0.90, metro: "Greenville, SC", state: "SC" },
  "294": { multiplier: 0.95, metro: "Charleston, SC", state: "SC" },
  "295": { multiplier: 0.85, metro: "South Carolina", state: "SC" },
  "296": { multiplier: 0.90, metro: "Greenville, SC", state: "SC" },
  "297": { multiplier: 0.90, metro: "South Carolina", state: "SC" },
  "298": { multiplier: 0.90, metro: "Augusta, GA", state: "GA" },
  "299": { multiplier: 0.85, metro: "South Carolina", state: "SC" },
  "300": { multiplier: 0.95, metro: "Atlanta", state: "GA" },
  "301": { multiplier: 0.95, metro: "Atlanta", state: "GA" },
  "302": { multiplier: 0.95, metro: "Atlanta", state: "GA" },
  "303": { multiplier: 0.95, metro: "Atlanta (Buckhead)", state: "GA" },
  "304": { multiplier: 0.85, metro: "Georgia (N)", state: "GA" },
  "305": { multiplier: 0.85, metro: "Athens", state: "GA" },
  "306": { multiplier: 0.85, metro: "Athens area", state: "GA" },
  "307": { multiplier: 0.85, metro: "Georgia (N)", state: "GA" },
  "308": { multiplier: 0.85, metro: "Georgia (N)", state: "GA" },
  "309": { multiplier: 0.85, metro: "Georgia (south)", state: "GA" },
  "310": { multiplier: 0.85, metro: "Augusta", state: "GA" },
  "311": { multiplier: 0.85, metro: "Augusta", state: "GA" },
  "312": { multiplier: 0.85, metro: "Macon", state: "GA" },
  "313": { multiplier: 0.85, metro: "Macon area", state: "GA" },
  "314": { multiplier: 0.85, metro: "Albany, GA", state: "GA" },
  "315": { multiplier: 0.85, metro: "Georgia (south)", state: "GA" },
  "316": { multiplier: 0.85, metro: "Valdosta", state: "GA" },
  "317": { multiplier: 0.85, metro: "Albany, GA", state: "GA" },
  "318": { multiplier: 0.90, metro: "Savannah", state: "GA" },
  "319": { multiplier: 0.85, metro: "Georgia (coastal)", state: "GA" },
  "320": { multiplier: 0.90, metro: "Jacksonville", state: "FL" },
  "321": { multiplier: 0.95, metro: "Daytona/Cocoa", state: "FL" },
  "322": { multiplier: 0.90, metro: "Jacksonville", state: "FL" },
  "323": { multiplier: 0.85, metro: "Tallahassee", state: "FL" },
  "324": { multiplier: 0.85, metro: "FL panhandle", state: "FL" },
  "325": { multiplier: 0.85, metro: "Pensacola", state: "FL" },
  "326": { multiplier: 0.85, metro: "Gainesville", state: "FL" },
  "327": { multiplier: 0.95, metro: "Orlando", state: "FL" },
  "328": { multiplier: 0.95, metro: "Orlando", state: "FL" },
  "329": { multiplier: 0.95, metro: "Melbourne area", state: "FL" },
  "330": { multiplier: 1.05, metro: "Miami", state: "FL" },
  "331": { multiplier: 1.05, metro: "Miami", state: "FL" },
  "332": { multiplier: 1.05, metro: "Miami Beach", state: "FL" },
  "333": { multiplier: 1.05, metro: "Fort Lauderdale", state: "FL" },
  "334": { multiplier: 1.05, metro: "West Palm Beach", state: "FL" },
  "335": { multiplier: 0.95, metro: "Tampa", state: "FL" },
  "336": { multiplier: 0.95, metro: "Tampa Bay", state: "FL" },
  "337": { multiplier: 0.95, metro: "St. Petersburg", state: "FL" },
  "338": { multiplier: 0.90, metro: "Lakeland area", state: "FL" },
  "339": { multiplier: 1.00, metro: "Fort Myers", state: "FL" },
  "350": { multiplier: 0.85, metro: "Birmingham", state: "AL" },
  "351": { multiplier: 0.85, metro: "Birmingham", state: "AL" },
  "352": { multiplier: 0.85, metro: "Birmingham", state: "AL" },
  "353": { multiplier: 0.85, metro: "Tuscaloosa", state: "AL" },
  "354": { multiplier: 0.80, metro: "Alabama (W)", state: "AL" },
  "355": { multiplier: 0.85, metro: "Huntsville", state: "AL" },
  "356": { multiplier: 0.80, metro: "Decatur, AL", state: "AL" },
  "357": { multiplier: 0.85, metro: "Huntsville", state: "AL" },
  "358": { multiplier: 0.80, metro: "AL (N)", state: "AL" },
  "359": { multiplier: 0.80, metro: "Alabama (N)", state: "AL" },
  "360": { multiplier: 0.85, metro: "Montgomery", state: "AL" },
  "361": { multiplier: 0.85, metro: "Montgomery", state: "AL" },
  "362": { multiplier: 0.80, metro: "Alabama (E)", state: "AL" },
  "363": { multiplier: 0.80, metro: "Dothan", state: "AL" },
  "364": { multiplier: 0.80, metro: "Alabama (S)", state: "AL" },
  "365": { multiplier: 0.85, metro: "Mobile", state: "AL" },
  "366": { multiplier: 0.85, metro: "Mobile", state: "AL" },
  "367": { multiplier: 0.85, metro: "Auburn", state: "AL" },
  "368": { multiplier: 0.80, metro: "AL (E)", state: "AL" },
  "369": { multiplier: 0.85, metro: "Mississippi (E)", state: "MS" },
  "370": { multiplier: 0.85, metro: "Nashville (E)", state: "TN" },
  "371": { multiplier: 0.90, metro: "Nashville", state: "TN" },
  "372": { multiplier: 0.95, metro: "Nashville", state: "TN" },
  "373": { multiplier: 0.85, metro: "Chattanooga", state: "TN" },
  "374": { multiplier: 0.85, metro: "Chattanooga", state: "TN" },
  "375": { multiplier: 0.85, metro: "Memphis", state: "TN" },
  "376": { multiplier: 0.85, metro: "TN (E)", state: "TN" },
  "377": { multiplier: 0.85, metro: "Knoxville", state: "TN" },
  "378": { multiplier: 0.85, metro: "Knoxville", state: "TN" },
  "379": { multiplier: 0.80, metro: "Tri-Cities (TN)", state: "TN" },
  "380": { multiplier: 0.85, metro: "Memphis", state: "TN" },
  "381": { multiplier: 0.85, metro: "Memphis", state: "TN" },
  "382": { multiplier: 0.80, metro: "TN (W)", state: "TN" },
  "383": { multiplier: 0.80, metro: "TN (W)", state: "TN" },
  "384": { multiplier: 0.85, metro: "Memphis area", state: "TN" },
  "385": { multiplier: 0.80, metro: "TN (rural)", state: "TN" },
  "386": { multiplier: 0.75, metro: "Mississippi Delta", state: "MS" },
  "387": { multiplier: 0.75, metro: "Mississippi Delta", state: "MS" },
  "388": { multiplier: 0.75, metro: "Mississippi Delta", state: "MS" },
  "389": { multiplier: 0.75, metro: "Mississippi Delta", state: "MS" },
  "390": { multiplier: 0.85, metro: "Jackson, MS", state: "MS" },
  "391": { multiplier: 0.80, metro: "Jackson, MS", state: "MS" },
  "392": { multiplier: 0.85, metro: "Jackson, MS", state: "MS" },
  "393": { multiplier: 0.80, metro: "Mississippi", state: "MS" },
  "394": { multiplier: 0.80, metro: "Mississippi", state: "MS" },
  "395": { multiplier: 0.80, metro: "Mississippi (S)", state: "MS" },
  "396": { multiplier: 0.85, metro: "Gulfport", state: "MS" },
  "397": { multiplier: 0.80, metro: "MS (E)", state: "MS" },
  "398": { multiplier: 0.85, metro: "Columbus, GA", state: "GA" },
  "400": { multiplier: 0.85, metro: "Louisville", state: "KY" },
  "401": { multiplier: 0.85, metro: "Louisville", state: "KY" },
  "402": { multiplier: 0.85, metro: "Louisville", state: "KY" },
  "403": { multiplier: 0.80, metro: "Lexington area", state: "KY" },
  "404": { multiplier: 0.80, metro: "KY", state: "KY" },
  "405": { multiplier: 0.85, metro: "Lexington", state: "KY" },
  "406": { multiplier: 0.85, metro: "Lexington", state: "KY" },
  "407": { multiplier: 0.80, metro: "KY (E)", state: "KY" },
  "408": { multiplier: 0.80, metro: "KY (E)", state: "KY" },
  "409": { multiplier: 0.80, metro: "KY (E)", state: "KY" },
  "410": { multiplier: 0.80, metro: "Cincinnati, OH (S)", state: "KY" },
  "411": { multiplier: 0.85, metro: "Ashland, KY", state: "KY" },
  "412": { multiplier: 0.80, metro: "KY (NE)", state: "KY" },
  "413": { multiplier: 0.80, metro: "KY", state: "KY" },
  "414": { multiplier: 0.80, metro: "KY", state: "KY" },
  "415": { multiplier: 0.80, metro: "KY (E)", state: "KY" },
  "416": { multiplier: 0.80, metro: "Pikeville, KY", state: "KY" },
  "417": { multiplier: 0.80, metro: "KY", state: "KY" },
  "418": { multiplier: 0.80, metro: "KY", state: "KY" },
  "420": { multiplier: 0.80, metro: "KY (W)", state: "KY" },
  "421": { multiplier: 0.80, metro: "Bowling Green, KY", state: "KY" },
  "422": { multiplier: 0.80, metro: "KY", state: "KY" },
  "423": { multiplier: 0.85, metro: "Owensboro", state: "KY" },
  "424": { multiplier: 0.80, metro: "KY (W)", state: "KY" },
  "425": { multiplier: 0.80, metro: "Paducah", state: "KY" },
  "426": { multiplier: 0.80, metro: "KY", state: "KY" },
  "427": { multiplier: 0.80, metro: "KY", state: "KY" },

  // -------------------------------------------------------------
  // OHIO / INDIANA / MICHIGAN / WISCONSIN / ILLINOIS
  // -------------------------------------------------------------
  "430": { multiplier: 0.85, metro: "Columbus, OH", state: "OH" },
  "431": { multiplier: 0.85, metro: "Columbus, OH", state: "OH" },
  "432": { multiplier: 0.85, metro: "Columbus, OH", state: "OH" },
  "433": { multiplier: 0.85, metro: "Columbus, OH", state: "OH" },
  "434": { multiplier: 0.85, metro: "Toledo, OH", state: "OH" },
  "435": { multiplier: 0.85, metro: "Toledo", state: "OH" },
  "436": { multiplier: 0.80, metro: "OH (N)", state: "OH" },
  "437": { multiplier: 0.85, metro: "Zanesville", state: "OH" },
  "438": { multiplier: 0.85, metro: "Mansfield", state: "OH" },
  "439": { multiplier: 0.85, metro: "Mansfield", state: "OH" },
  "440": { multiplier: 0.85, metro: "Cleveland", state: "OH" },
  "441": { multiplier: 0.85, metro: "Cleveland", state: "OH" },
  "442": { multiplier: 0.85, metro: "Akron", state: "OH" },
  "443": { multiplier: 0.85, metro: "Akron", state: "OH" },
  "444": { multiplier: 0.85, metro: "Youngstown", state: "OH" },
  "445": { multiplier: 0.85, metro: "Youngstown", state: "OH" },
  "446": { multiplier: 0.85, metro: "Canton", state: "OH" },
  "447": { multiplier: 0.85, metro: "Canton area", state: "OH" },
  "448": { multiplier: 0.80, metro: "Mansfield area", state: "OH" },
  "449": { multiplier: 0.80, metro: "OH (NW)", state: "OH" },
  "450": { multiplier: 0.85, metro: "Cincinnati", state: "OH" },
  "451": { multiplier: 0.85, metro: "Cincinnati", state: "OH" },
  "452": { multiplier: 0.85, metro: "Cincinnati", state: "OH" },
  "453": { multiplier: 0.85, metro: "Dayton", state: "OH" },
  "454": { multiplier: 0.85, metro: "Dayton", state: "OH" },
  "455": { multiplier: 0.85, metro: "Springfield, OH", state: "OH" },
  "456": { multiplier: 0.85, metro: "Chillicothe", state: "OH" },
  "457": { multiplier: 0.80, metro: "OH (SE)", state: "OH" },
  "458": { multiplier: 0.85, metro: "Lima", state: "OH" },
  "459": { multiplier: 0.80, metro: "OH (W)", state: "OH" },
  "460": { multiplier: 0.85, metro: "Indianapolis", state: "IN" },
  "461": { multiplier: 0.85, metro: "Indianapolis", state: "IN" },
  "462": { multiplier: 0.85, metro: "Indianapolis", state: "IN" },
  "463": { multiplier: 0.85, metro: "Gary, IN", state: "IN" },
  "464": { multiplier: 0.85, metro: "Gary, IN", state: "IN" },
  "465": { multiplier: 0.85, metro: "South Bend, IN", state: "IN" },
  "466": { multiplier: 0.85, metro: "South Bend", state: "IN" },
  "467": { multiplier: 0.85, metro: "Fort Wayne", state: "IN" },
  "468": { multiplier: 0.85, metro: "Fort Wayne", state: "IN" },
  "469": { multiplier: 0.85, metro: "Kokomo", state: "IN" },
  "470": { multiplier: 0.85, metro: "Cincinnati area (IN)", state: "IN" },
  "471": { multiplier: 0.85, metro: "IN (S)", state: "IN" },
  "472": { multiplier: 0.85, metro: "Columbus, IN", state: "IN" },
  "473": { multiplier: 0.85, metro: "IN (S)", state: "IN" },
  "474": { multiplier: 0.85, metro: "Bloomington, IN", state: "IN" },
  "475": { multiplier: 0.85, metro: "Washington, IN", state: "IN" },
  "476": { multiplier: 0.85, metro: "Evansville", state: "IN" },
  "477": { multiplier: 0.85, metro: "Evansville", state: "IN" },
  "478": { multiplier: 0.85, metro: "Terre Haute", state: "IN" },
  "479": { multiplier: 0.85, metro: "Lafayette, IN", state: "IN" },
  "480": { multiplier: 0.90, metro: "Detroit (suburbs)", state: "MI" },
  "481": { multiplier: 0.85, metro: "Detroit", state: "MI" },
  "482": { multiplier: 0.85, metro: "Detroit", state: "MI" },
  "483": { multiplier: 0.85, metro: "Royal Oak / Pontiac", state: "MI" },
  "484": { multiplier: 0.85, metro: "Flint", state: "MI" },
  "485": { multiplier: 0.85, metro: "Flint", state: "MI" },
  "486": { multiplier: 0.85, metro: "Saginaw", state: "MI" },
  "487": { multiplier: 0.85, metro: "Saginaw / Bay City", state: "MI" },
  "488": { multiplier: 0.90, metro: "Lansing", state: "MI" },
  "489": { multiplier: 0.95, metro: "Ann Arbor", state: "MI" },
  "490": { multiplier: 0.85, metro: "Kalamazoo", state: "MI" },
  "491": { multiplier: 0.85, metro: "Kalamazoo", state: "MI" },
  "492": { multiplier: 0.85, metro: "Jackson, MI", state: "MI" },
  "493": { multiplier: 0.85, metro: "Grand Rapids", state: "MI" },
  "494": { multiplier: 0.85, metro: "Muskegon", state: "MI" },
  "495": { multiplier: 0.85, metro: "Grand Rapids", state: "MI" },
  "496": { multiplier: 0.85, metro: "MI (N)", state: "MI" },
  "497": { multiplier: 0.85, metro: "Traverse City", state: "MI" },
  "498": { multiplier: 0.85, metro: "MI (UP)", state: "MI" },
  "499": { multiplier: 0.85, metro: "MI (UP)", state: "MI" },
  "500": { multiplier: 0.85, metro: "Des Moines", state: "IA" },
  "501": { multiplier: 0.85, metro: "Des Moines", state: "IA" },
  "502": { multiplier: 0.85, metro: "Des Moines", state: "IA" },
  "503": { multiplier: 0.85, metro: "Des Moines", state: "IA" },
  "504": { multiplier: 0.85, metro: "Mason City", state: "IA" },
  "505": { multiplier: 0.85, metro: "Mason City", state: "IA" },
  "506": { multiplier: 0.85, metro: "Cedar Rapids", state: "IA" },
  "507": { multiplier: 0.85, metro: "Cedar Rapids", state: "IA" },
  "508": { multiplier: 0.85, metro: "Iowa", state: "IA" },
  "509": { multiplier: 0.80, metro: "Iowa", state: "IA" },
  "510": { multiplier: 0.85, metro: "Sioux City", state: "IA" },
  "511": { multiplier: 0.80, metro: "Sioux City", state: "IA" },
  "512": { multiplier: 0.85, metro: "Iowa", state: "IA" },
  "513": { multiplier: 0.80, metro: "Iowa", state: "IA" },
  "514": { multiplier: 0.85, metro: "Iowa", state: "IA" },
  "515": { multiplier: 0.80, metro: "Iowa", state: "IA" },
  "516": { multiplier: 0.85, metro: "Davenport area", state: "IA" },
  "520": { multiplier: 0.90, metro: "Milwaukee suburbs", state: "WI" },
  "530": { multiplier: 0.95, metro: "Milwaukee", state: "WI" },
  "531": { multiplier: 0.95, metro: "Milwaukee", state: "WI" },
  "532": { multiplier: 0.95, metro: "Milwaukee", state: "WI" },
  "534": { multiplier: 0.90, metro: "Racine, WI", state: "WI" },
  "535": { multiplier: 0.95, metro: "Madison", state: "WI" },
  "537": { multiplier: 0.90, metro: "WI (south)", state: "WI" },
  "538": { multiplier: 0.85, metro: "WI", state: "WI" },
  "539": { multiplier: 0.85, metro: "WI", state: "WI" },
  "540": { multiplier: 0.85, metro: "WI", state: "WI" },
  "541": { multiplier: 0.85, metro: "Green Bay", state: "WI" },
  "542": { multiplier: 0.85, metro: "Green Bay", state: "WI" },
  "543": { multiplier: 0.85, metro: "Wausau, WI", state: "WI" },
  "544": { multiplier: 0.85, metro: "WI (north)", state: "WI" },
  "545": { multiplier: 0.85, metro: "WI (north)", state: "WI" },
  "546": { multiplier: 0.85, metro: "WI (north)", state: "WI" },
  "547": { multiplier: 0.85, metro: "WI (north)", state: "WI" },
  "548": { multiplier: 0.85, metro: "WI (north)", state: "WI" },
  "549": { multiplier: 0.85, metro: "Oshkosh", state: "WI" },
  "550": { multiplier: 0.95, metro: "Minneapolis", state: "MN" },
  "551": { multiplier: 0.95, metro: "St. Paul", state: "MN" },
  "552": { multiplier: 0.95, metro: "Minneapolis", state: "MN" },
  "553": { multiplier: 0.95, metro: "Minneapolis", state: "MN" },
  "554": { multiplier: 0.95, metro: "Minneapolis suburbs", state: "MN" },
  "555": { multiplier: 0.90, metro: "Minneapolis suburbs", state: "MN" },
  "556": { multiplier: 0.85, metro: "Duluth", state: "MN" },
  "557": { multiplier: 0.85, metro: "Duluth", state: "MN" },
  "558": { multiplier: 0.85, metro: "Duluth", state: "MN" },
  "559": { multiplier: 0.85, metro: "Rochester, MN", state: "MN" },
  "560": { multiplier: 0.85, metro: "Mankato", state: "MN" },
  "561": { multiplier: 0.85, metro: "MN", state: "MN" },
  "562": { multiplier: 0.85, metro: "MN", state: "MN" },
  "563": { multiplier: 0.85, metro: "St. Cloud", state: "MN" },
  "564": { multiplier: 0.85, metro: "Brainerd", state: "MN" },
  "565": { multiplier: 0.85, metro: "MN", state: "MN" },
  "566": { multiplier: 0.85, metro: "MN", state: "MN" },
  "567": { multiplier: 0.85, metro: "MN", state: "MN" },
  "600": { multiplier: 1.00, metro: "Chicago suburbs", state: "IL" },
  "601": { multiplier: 1.00, metro: "Chicago suburbs", state: "IL" },
  "602": { multiplier: 1.00, metro: "Chicago suburbs", state: "IL" },
  "603": { multiplier: 1.00, metro: "Chicago suburbs (W)", state: "IL" },
  "604": { multiplier: 1.00, metro: "Chicago suburbs", state: "IL" },
  "605": { multiplier: 1.00, metro: "Chicago suburbs", state: "IL" },
  "606": { multiplier: 1.10, metro: "Chicago", state: "IL" },
  "607": { multiplier: 1.05, metro: "Chicago", state: "IL" },
  "608": { multiplier: 1.05, metro: "Chicago suburbs", state: "IL" },
  "610": { multiplier: 0.85, metro: "Rockford, IL", state: "IL" },
  "611": { multiplier: 0.85, metro: "Rockford", state: "IL" },
  "612": { multiplier: 0.85, metro: "IL (N)", state: "IL" },
  "613": { multiplier: 0.85, metro: "LaSalle", state: "IL" },
  "614": { multiplier: 0.85, metro: "Galesburg", state: "IL" },
  "615": { multiplier: 0.85, metro: "Peoria", state: "IL" },
  "616": { multiplier: 0.85, metro: "Peoria", state: "IL" },
  "617": { multiplier: 0.85, metro: "Bloomington, IL", state: "IL" },
  "618": { multiplier: 0.85, metro: "Champaign-Urbana", state: "IL" },
  "619": { multiplier: 0.85, metro: "Champaign-Urbana", state: "IL" },
  "620": { multiplier: 0.85, metro: "Springfield, IL", state: "IL" },
  "622": { multiplier: 0.85, metro: "St. Louis area (E)", state: "IL" },
  "623": { multiplier: 0.85, metro: "Decatur", state: "IL" },
  "624": { multiplier: 0.80, metro: "IL (S)", state: "IL" },
  "625": { multiplier: 0.85, metro: "Springfield, IL", state: "IL" },
  "626": { multiplier: 0.85, metro: "Springfield, IL", state: "IL" },
  "627": { multiplier: 0.85, metro: "IL", state: "IL" },
  "628": { multiplier: 0.85, metro: "Centralia", state: "IL" },
  "629": { multiplier: 0.85, metro: "IL (S)", state: "IL" },
  "630": { multiplier: 0.90, metro: "St. Louis", state: "MO" },
  "631": { multiplier: 0.90, metro: "St. Louis", state: "MO" },
  "633": { multiplier: 0.85, metro: "St. Louis suburbs", state: "MO" },
  "634": { multiplier: 0.85, metro: "MO (E)", state: "MO" },
  "635": { multiplier: 0.85, metro: "MO", state: "MO" },
  "636": { multiplier: 0.85, metro: "St. Louis (W suburbs)", state: "MO" },
  "637": { multiplier: 0.85, metro: "Cape Girardeau", state: "MO" },
  "638": { multiplier: 0.85, metro: "MO (SE)", state: "MO" },
  "639": { multiplier: 0.85, metro: "MO", state: "MO" },
  "640": { multiplier: 0.85, metro: "Kansas City suburbs (MO)", state: "MO" },
  "641": { multiplier: 0.85, metro: "Kansas City, MO", state: "MO" },
  "644": { multiplier: 0.85, metro: "St. Joseph, MO", state: "MO" },
  "645": { multiplier: 0.85, metro: "St. Joseph", state: "MO" },
  "646": { multiplier: 0.80, metro: "MO", state: "MO" },
  "647": { multiplier: 0.80, metro: "MO", state: "MO" },
  "648": { multiplier: 0.80, metro: "MO (S)", state: "MO" },
  "649": { multiplier: 0.85, metro: "Columbia, MO", state: "MO" },
  "650": { multiplier: 0.85, metro: "Jefferson City, MO", state: "MO" },
  "651": { multiplier: 0.85, metro: "Jefferson City", state: "MO" },
  "652": { multiplier: 0.85, metro: "Columbia", state: "MO" },
  "653": { multiplier: 0.85, metro: "MO (central)", state: "MO" },
  "654": { multiplier: 0.85, metro: "MO", state: "MO" },
  "655": { multiplier: 0.85, metro: "MO", state: "MO" },
  "656": { multiplier: 0.85, metro: "Springfield, MO", state: "MO" },
  "657": { multiplier: 0.85, metro: "Springfield, MO", state: "MO" },
  "658": { multiplier: 0.85, metro: "Springfield, MO", state: "MO" },
  "660": { multiplier: 0.85, metro: "Kansas City suburbs (KS)", state: "KS" },
  "661": { multiplier: 0.85, metro: "Kansas City, KS", state: "KS" },
  "662": { multiplier: 0.85, metro: "Kansas City suburbs", state: "KS" },
  "664": { multiplier: 0.85, metro: "Topeka", state: "KS" },
  "665": { multiplier: 0.85, metro: "Topeka", state: "KS" },
  "667": { multiplier: 0.80, metro: "Kansas (N)", state: "KS" },
  "668": { multiplier: 0.80, metro: "Kansas (W)", state: "KS" },
  "669": { multiplier: 0.85, metro: "Salina", state: "KS" },
  "670": { multiplier: 0.85, metro: "Wichita", state: "KS" },
  "671": { multiplier: 0.85, metro: "Wichita", state: "KS" },
  "672": { multiplier: 0.80, metro: "Wichita area", state: "KS" },
  "673": { multiplier: 0.80, metro: "Independence, KS", state: "KS" },
  "674": { multiplier: 0.80, metro: "Salina", state: "KS" },
  "675": { multiplier: 0.80, metro: "Hutchinson", state: "KS" },
  "676": { multiplier: 0.80, metro: "Hays, KS", state: "KS" },
  "677": { multiplier: 0.80, metro: "Colby, KS", state: "KS" },
  "678": { multiplier: 0.80, metro: "Dodge City", state: "KS" },
  "679": { multiplier: 0.80, metro: "Liberal, KS", state: "KS" },
  "680": { multiplier: 0.85, metro: "Omaha", state: "NE" },
  "681": { multiplier: 0.85, metro: "Omaha", state: "NE" },
  "683": { multiplier: 0.85, metro: "Lincoln, NE", state: "NE" },
  "684": { multiplier: 0.85, metro: "Lincoln", state: "NE" },
  "685": { multiplier: 0.85, metro: "Lincoln area", state: "NE" },
  "686": { multiplier: 0.80, metro: "NE (E)", state: "NE" },
  "687": { multiplier: 0.80, metro: "Norfolk, NE", state: "NE" },
  "688": { multiplier: 0.80, metro: "Grand Island", state: "NE" },
  "689": { multiplier: 0.80, metro: "Hastings, NE", state: "NE" },
  "690": { multiplier: 0.80, metro: "McCook, NE", state: "NE" },
  "691": { multiplier: 0.80, metro: "North Platte", state: "NE" },
  "692": { multiplier: 0.80, metro: "NE (W)", state: "NE" },
  "693": { multiplier: 0.80, metro: "Alliance, NE", state: "NE" },

  // -------------------------------------------------------------
  // SOUTH-CENTRAL — Texas, Oklahoma, Arkansas, Louisiana
  // -------------------------------------------------------------
  "700": { multiplier: 0.95, metro: "New Orleans", state: "LA" },
  "701": { multiplier: 0.95, metro: "New Orleans", state: "LA" },
  "703": { multiplier: 0.85, metro: "Thibodaux area", state: "LA" },
  "704": { multiplier: 0.85, metro: "Houma", state: "LA" },
  "705": { multiplier: 0.85, metro: "Lafayette, LA", state: "LA" },
  "706": { multiplier: 0.85, metro: "Lake Charles", state: "LA" },
  "707": { multiplier: 0.85, metro: "Baton Rouge", state: "LA" },
  "708": { multiplier: 0.85, metro: "Baton Rouge", state: "LA" },
  "710": { multiplier: 0.85, metro: "Shreveport", state: "LA" },
  "711": { multiplier: 0.85, metro: "Shreveport", state: "LA" },
  "712": { multiplier: 0.85, metro: "Monroe, LA", state: "LA" },
  "713": { multiplier: 0.80, metro: "Alexandria, LA", state: "LA" },
  "714": { multiplier: 0.80, metro: "Alexandria, LA", state: "LA" },
  "716": { multiplier: 0.85, metro: "Pine Bluff, AR", state: "AR" },
  "717": { multiplier: 0.85, metro: "Camden, AR", state: "AR" },
  "718": { multiplier: 0.85, metro: "Texarkana", state: "AR" },
  "719": { multiplier: 0.85, metro: "Hot Springs", state: "AR" },
  "720": { multiplier: 0.85, metro: "Little Rock", state: "AR" },
  "721": { multiplier: 0.85, metro: "Little Rock", state: "AR" },
  "722": { multiplier: 0.85, metro: "Little Rock", state: "AR" },
  "723": { multiplier: 0.85, metro: "West Memphis", state: "AR" },
  "724": { multiplier: 0.80, metro: "AR (NE)", state: "AR" },
  "725": { multiplier: 0.80, metro: "Batesville, AR", state: "AR" },
  "726": { multiplier: 0.80, metro: "Harrison, AR", state: "AR" },
  "727": { multiplier: 0.85, metro: "Fayetteville, AR", state: "AR" },
  "728": { multiplier: 0.85, metro: "Russellville, AR", state: "AR" },
  "729": { multiplier: 0.80, metro: "Fort Smith, AR", state: "AR" },
  "730": { multiplier: 0.85, metro: "Oklahoma City", state: "OK" },
  "731": { multiplier: 0.85, metro: "Oklahoma City", state: "OK" },
  "734": { multiplier: 0.80, metro: "Ardmore, OK", state: "OK" },
  "735": { multiplier: 0.80, metro: "Lawton", state: "OK" },
  "736": { multiplier: 0.80, metro: "Clinton, OK", state: "OK" },
  "737": { multiplier: 0.80, metro: "Enid, OK", state: "OK" },
  "738": { multiplier: 0.80, metro: "Woodward, OK", state: "OK" },
  "739": { multiplier: 0.80, metro: "Guymon, OK", state: "OK" },
  "740": { multiplier: 0.85, metro: "Tulsa", state: "OK" },
  "741": { multiplier: 0.85, metro: "Tulsa", state: "OK" },
  "743": { multiplier: 0.80, metro: "Bartlesville, OK", state: "OK" },
  "744": { multiplier: 0.80, metro: "Muskogee, OK", state: "OK" },
  "745": { multiplier: 0.80, metro: "McAlester", state: "OK" },
  "746": { multiplier: 0.80, metro: "Ponca City", state: "OK" },
  "747": { multiplier: 0.80, metro: "Durant, OK", state: "OK" },
  "748": { multiplier: 0.80, metro: "Shawnee", state: "OK" },
  "749": { multiplier: 0.80, metro: "Poteau, OK", state: "OK" },
  "750": { multiplier: 0.95, metro: "Dallas", state: "TX" },
  "751": { multiplier: 0.95, metro: "Dallas", state: "TX" },
  "752": { multiplier: 0.95, metro: "Dallas", state: "TX" },
  "753": { multiplier: 0.95, metro: "Dallas", state: "TX" },
  "754": { multiplier: 0.95, metro: "Greenville, TX", state: "TX" },
  "755": { multiplier: 0.85, metro: "Texarkana", state: "TX" },
  "756": { multiplier: 0.85, metro: "Longview", state: "TX" },
  "757": { multiplier: 0.85, metro: "Tyler, TX", state: "TX" },
  "758": { multiplier: 0.85, metro: "Palestine, TX", state: "TX" },
  "759": { multiplier: 0.85, metro: "Lufkin, TX", state: "TX" },
  "760": { multiplier: 0.95, metro: "Fort Worth", state: "TX" },
  "761": { multiplier: 0.95, metro: "Fort Worth", state: "TX" },
  "762": { multiplier: 0.95, metro: "Fort Worth area", state: "TX" },
  "763": { multiplier: 0.85, metro: "Wichita Falls, TX", state: "TX" },
  "764": { multiplier: 0.85, metro: "Wichita Falls", state: "TX" },
  "765": { multiplier: 0.85, metro: "Waco area", state: "TX" },
  "766": { multiplier: 0.85, metro: "Waco", state: "TX" },
  "767": { multiplier: 0.85, metro: "Waco area", state: "TX" },
  "768": { multiplier: 0.85, metro: "Brownwood, TX", state: "TX" },
  "769": { multiplier: 0.85, metro: "Abilene", state: "TX" },
  "770": { multiplier: 0.95, metro: "Houston", state: "TX" },
  "771": { multiplier: 0.95, metro: "Houston", state: "TX" },
  "772": { multiplier: 0.95, metro: "Houston", state: "TX" },
  "773": { multiplier: 0.90, metro: "Houston suburbs", state: "TX" },
  "774": { multiplier: 0.90, metro: "Bay Area (Houston)", state: "TX" },
  "775": { multiplier: 0.90, metro: "Houston suburbs", state: "TX" },
  "776": { multiplier: 0.85, metro: "Beaumont", state: "TX" },
  "777": { multiplier: 0.85, metro: "Beaumont", state: "TX" },
  "778": { multiplier: 0.85, metro: "Bryan/College Station", state: "TX" },
  "779": { multiplier: 0.85, metro: "Victoria, TX", state: "TX" },
  "780": { multiplier: 0.85, metro: "Corpus Christi", state: "TX" },
  "781": { multiplier: 0.90, metro: "San Antonio", state: "TX" },
  "782": { multiplier: 0.90, metro: "San Antonio", state: "TX" },
  "783": { multiplier: 0.85, metro: "Corpus Christi", state: "TX" },
  "784": { multiplier: 0.85, metro: "Corpus Christi", state: "TX" },
  "785": { multiplier: 0.85, metro: "McAllen", state: "TX" },
  "786": { multiplier: 1.00, metro: "Austin", state: "TX" },
  "787": { multiplier: 1.00, metro: "Austin", state: "TX" },
  "788": { multiplier: 0.85, metro: "Del Rio area", state: "TX" },
  "789": { multiplier: 0.85, metro: "Giddings, TX", state: "TX" },
  "790": { multiplier: 0.80, metro: "Amarillo", state: "TX" },
  "791": { multiplier: 0.80, metro: "Amarillo", state: "TX" },
  "792": { multiplier: 0.80, metro: "Childress, TX", state: "TX" },
  "793": { multiplier: 0.80, metro: "Lubbock", state: "TX" },
  "794": { multiplier: 0.80, metro: "Lubbock", state: "TX" },
  "795": { multiplier: 0.80, metro: "Abilene, TX", state: "TX" },
  "796": { multiplier: 0.80, metro: "Midland", state: "TX" },
  "797": { multiplier: 0.80, metro: "Odessa", state: "TX" },
  "798": { multiplier: 0.80, metro: "El Paso", state: "TX" },
  "799": { multiplier: 0.80, metro: "El Paso", state: "TX" },

  // -------------------------------------------------------------
  // MOUNTAIN WEST — Colorado, Wyoming, Montana, Idaho, Utah,
  // Arizona, New Mexico, Nevada
  // -------------------------------------------------------------
  "800": { multiplier: 1.05, metro: "Denver", state: "CO" },
  "801": { multiplier: 1.05, metro: "Denver", state: "CO" },
  "802": { multiplier: 1.05, metro: "Denver", state: "CO" },
  "803": { multiplier: 1.10, metro: "Boulder", state: "CO" },
  "804": { multiplier: 1.00, metro: "Denver suburbs", state: "CO" },
  "805": { multiplier: 0.95, metro: "Fort Collins", state: "CO" },
  "806": { multiplier: 0.90, metro: "Greeley", state: "CO" },
  "807": { multiplier: 0.85, metro: "CO (NW)", state: "CO" },
  "808": { multiplier: 0.95, metro: "Colorado Springs", state: "CO" },
  "809": { multiplier: 0.95, metro: "Pueblo", state: "CO" },
  "810": { multiplier: 0.85, metro: "Pueblo", state: "CO" },
  "811": { multiplier: 0.95, metro: "Colorado Mountains", state: "CO" },
  "812": { multiplier: 0.85, metro: "Salida", state: "CO" },
  "813": { multiplier: 0.85, metro: "Durango area", state: "CO" },
  "814": { multiplier: 0.85, metro: "Grand Junction", state: "CO" },
  "815": { multiplier: 0.85, metro: "Grand Junction", state: "CO" },
  "816": { multiplier: 0.85, metro: "CO (W)", state: "CO" },
  "820": { multiplier: 0.85, metro: "Cheyenne", state: "WY" },
  "821": { multiplier: 0.85, metro: "WY", state: "WY" },
  "822": { multiplier: 0.85, metro: "Wheatland, WY", state: "WY" },
  "823": { multiplier: 0.90, metro: "Rawlins", state: "WY" },
  "824": { multiplier: 0.85, metro: "WY (W)", state: "WY" },
  "825": { multiplier: 0.95, metro: "Jackson, WY", state: "WY" },
  "826": { multiplier: 0.85, metro: "Casper", state: "WY" },
  "828": { multiplier: 0.85, metro: "Sheridan, WY", state: "WY" },
  "829": { multiplier: 0.85, metro: "Rock Springs", state: "WY" },
  "830": { multiplier: 0.85, metro: "Pocatello, ID", state: "ID" },
  "831": { multiplier: 0.85, metro: "Pocatello, ID", state: "ID" },
  "832": { multiplier: 0.85, metro: "Twin Falls, ID", state: "ID" },
  "833": { multiplier: 0.95, metro: "Boise", state: "ID" },
  "834": { multiplier: 0.85, metro: "ID", state: "ID" },
  "835": { multiplier: 0.85, metro: "Lewiston, ID", state: "ID" },
  "836": { multiplier: 0.95, metro: "Boise", state: "ID" },
  "837": { multiplier: 0.95, metro: "Boise area", state: "ID" },
  "838": { multiplier: 0.95, metro: "Coeur d'Alene", state: "ID" },
  "840": { multiplier: 0.95, metro: "Salt Lake City", state: "UT" },
  "841": { multiplier: 0.95, metro: "Salt Lake City", state: "UT" },
  "842": { multiplier: 0.95, metro: "Ogden", state: "UT" },
  "843": { multiplier: 0.95, metro: "Salt Lake City", state: "UT" },
  "844": { multiplier: 0.95, metro: "Provo", state: "UT" },
  "845": { multiplier: 0.95, metro: "Provo", state: "UT" },
  "846": { multiplier: 0.95, metro: "Utah", state: "UT" },
  "847": { multiplier: 0.95, metro: "St. George, UT", state: "UT" },
  "850": { multiplier: 0.95, metro: "Phoenix", state: "AZ" },
  "851": { multiplier: 0.95, metro: "Phoenix", state: "AZ" },
  "852": { multiplier: 0.95, metro: "Phoenix", state: "AZ" },
  "853": { multiplier: 0.95, metro: "Phoenix", state: "AZ" },
  "854": { multiplier: 0.85, metro: "Globe, AZ", state: "AZ" },
  "855": { multiplier: 0.85, metro: "AZ (rural)", state: "AZ" },
  "856": { multiplier: 0.85, metro: "Tucson", state: "AZ" },
  "857": { multiplier: 0.85, metro: "Tucson", state: "AZ" },
  "859": { multiplier: 0.85, metro: "Show Low, AZ", state: "AZ" },
  "860": { multiplier: 0.85, metro: "Flagstaff, AZ", state: "AZ" },
  "863": { multiplier: 0.85, metro: "Prescott", state: "AZ" },
  "864": { multiplier: 0.85, metro: "Kingman", state: "AZ" },
  "865": { multiplier: 0.85, metro: "Gallup, NM", state: "NM" },
  "870": { multiplier: 0.85, metro: "Albuquerque", state: "NM" },
  "871": { multiplier: 0.85, metro: "Albuquerque", state: "NM" },
  "873": { multiplier: 0.85, metro: "NM", state: "NM" },
  "874": { multiplier: 0.85, metro: "Farmington, NM", state: "NM" },
  "875": { multiplier: 0.95, metro: "Santa Fe", state: "NM" },
  "877": { multiplier: 0.85, metro: "NM", state: "NM" },
  "878": { multiplier: 0.85, metro: "Socorro", state: "NM" },
  "879": { multiplier: 0.85, metro: "Truth or Consequences", state: "NM" },
  "880": { multiplier: 0.85, metro: "Las Cruces", state: "NM" },
  "881": { multiplier: 0.85, metro: "Clovis, NM", state: "NM" },
  "882": { multiplier: 0.85, metro: "Roswell", state: "NM" },
  "883": { multiplier: 0.85, metro: "Carrizozo, NM", state: "NM" },
  "884": { multiplier: 0.85, metro: "Tucumcari", state: "NM" },
  "889": { multiplier: 1.00, metro: "Las Vegas", state: "NV" },
  "890": { multiplier: 1.00, metro: "Las Vegas", state: "NV" },
  "891": { multiplier: 1.00, metro: "Las Vegas", state: "NV" },
  "893": { multiplier: 0.85, metro: "Ely, NV", state: "NV" },
  "894": { multiplier: 1.00, metro: "Reno", state: "NV" },
  "895": { multiplier: 1.00, metro: "Reno", state: "NV" },
  "897": { multiplier: 0.85, metro: "Carson City", state: "NV" },
  "898": { multiplier: 0.90, metro: "Elko, NV", state: "NV" },

  // -------------------------------------------------------------
  // PACIFIC — California, Oregon, Washington, Alaska, Hawaii
  // -------------------------------------------------------------
  "900": { multiplier: 1.30, metro: "Los Angeles", state: "CA" },
  "901": { multiplier: 1.30, metro: "Los Angeles", state: "CA" },
  "902": { multiplier: 1.30, metro: "Beverly Hills/W LA", state: "CA" },
  "903": { multiplier: 1.30, metro: "Inglewood/Hawthorne", state: "CA" },
  "904": { multiplier: 1.30, metro: "Santa Monica", state: "CA" },
  "905": { multiplier: 1.25, metro: "Long Beach", state: "CA" },
  "906": { multiplier: 1.25, metro: "Long Beach area", state: "CA" },
  "907": { multiplier: 1.25, metro: "Long Beach", state: "CA" },
  "908": { multiplier: 1.25, metro: "Long Beach area", state: "CA" },
  "910": { multiplier: 1.20, metro: "Pasadena", state: "CA" },
  "911": { multiplier: 1.20, metro: "Pasadena", state: "CA" },
  "912": { multiplier: 1.20, metro: "Glendale", state: "CA" },
  "913": { multiplier: 1.20, metro: "Van Nuys / SF Valley", state: "CA" },
  "914": { multiplier: 1.20, metro: "San Fernando Valley", state: "CA" },
  "915": { multiplier: 1.20, metro: "Burbank/SF Valley", state: "CA" },
  "916": { multiplier: 1.20, metro: "North Hollywood", state: "CA" },
  "917": { multiplier: 1.15, metro: "Pomona/Alhambra", state: "CA" },
  "918": { multiplier: 1.15, metro: "Pomona/Alhambra", state: "CA" },
  "919": { multiplier: 1.25, metro: "San Diego", state: "CA" },
  "920": { multiplier: 1.25, metro: "San Diego", state: "CA" },
  "921": { multiplier: 1.25, metro: "San Diego", state: "CA" },
  "922": { multiplier: 1.05, metro: "Palm Springs", state: "CA" },
  "923": { multiplier: 1.05, metro: "San Bernardino", state: "CA" },
  "924": { multiplier: 1.05, metro: "San Bernardino", state: "CA" },
  "925": { multiplier: 1.10, metro: "Riverside", state: "CA" },
  "926": { multiplier: 1.30, metro: "Orange County", state: "CA" },
  "927": { multiplier: 1.30, metro: "Anaheim", state: "CA" },
  "928": { multiplier: 1.30, metro: "Anaheim/Santa Ana", state: "CA" },
  "930": { multiplier: 0.95, metro: "Bakersfield", state: "CA" },
  "931": { multiplier: 1.00, metro: "Santa Barbara", state: "CA" },
  "932": { multiplier: 0.95, metro: "Bakersfield", state: "CA" },
  "933": { multiplier: 0.95, metro: "Bakersfield", state: "CA" },
  "934": { multiplier: 1.05, metro: "Santa Barbara", state: "CA" },
  "935": { multiplier: 0.95, metro: "Mojave", state: "CA" },
  "936": { multiplier: 0.95, metro: "Fresno", state: "CA" },
  "937": { multiplier: 0.95, metro: "Fresno", state: "CA" },
  "938": { multiplier: 0.95, metro: "Fresno", state: "CA" },
  "939": { multiplier: 1.05, metro: "Salinas/Monterey", state: "CA" },
  "940": { multiplier: 1.50, metro: "San Francisco", state: "CA" },
  "941": { multiplier: 1.50, metro: "San Francisco", state: "CA" },
  "942": { multiplier: 1.10, metro: "Sacramento (W)", state: "CA" },
  "943": { multiplier: 1.45, metro: "Palo Alto/Peninsula", state: "CA" },
  "944": { multiplier: 1.45, metro: "San Mateo/Peninsula", state: "CA" },
  "945": { multiplier: 1.40, metro: "Oakland/East Bay", state: "CA" },
  "946": { multiplier: 1.40, metro: "Oakland", state: "CA" },
  "947": { multiplier: 1.40, metro: "Berkeley", state: "CA" },
  "948": { multiplier: 1.35, metro: "Richmond/Vallejo", state: "CA" },
  "949": { multiplier: 1.30, metro: "Larkspur/Marin", state: "CA" },
  "950": { multiplier: 1.45, metro: "San Jose", state: "CA" },
  "951": { multiplier: 1.45, metro: "San Jose", state: "CA" },
  "952": { multiplier: 1.30, metro: "Santa Cruz", state: "CA" },
  "953": { multiplier: 1.05, metro: "Stockton", state: "CA" },
  "954": { multiplier: 1.05, metro: "Santa Rosa", state: "CA" },
  "955": { multiplier: 1.05, metro: "Eureka, CA", state: "CA" },
  "956": { multiplier: 1.10, metro: "Sacramento", state: "CA" },
  "957": { multiplier: 1.10, metro: "Sacramento", state: "CA" },
  "958": { multiplier: 1.05, metro: "Sacramento area", state: "CA" },
  "959": { multiplier: 1.00, metro: "Sacramento (E)", state: "CA" },
  "960": { multiplier: 0.95, metro: "Redding", state: "CA" },
  "961": { multiplier: 0.95, metro: "Reno area (CA)", state: "CA" },
  "967": { multiplier: 1.50, metro: "Honolulu (Oahu)", state: "HI" },
  "968": { multiplier: 1.50, metro: "Honolulu", state: "HI" },
  "969": { multiplier: 1.45, metro: "Hawaii (other islands)", state: "HI" },
  "970": { multiplier: 1.05, metro: "Portland, OR", state: "OR" },
  "971": { multiplier: 1.05, metro: "Portland, OR", state: "OR" },
  "972": { multiplier: 1.10, metro: "Portland, OR", state: "OR" },
  "973": { multiplier: 0.95, metro: "Salem, OR", state: "OR" },
  "974": { multiplier: 0.95, metro: "Eugene", state: "OR" },
  "975": { multiplier: 0.90, metro: "Medford", state: "OR" },
  "976": { multiplier: 0.90, metro: "Klamath Falls", state: "OR" },
  "977": { multiplier: 0.90, metro: "Bend, OR", state: "OR" },
  "978": { multiplier: 0.90, metro: "Pendleton, OR", state: "OR" },
  "979": { multiplier: 0.85, metro: "OR (E)", state: "OR" },
  "980": { multiplier: 1.20, metro: "Seattle", state: "WA" },
  "981": { multiplier: 1.20, metro: "Seattle", state: "WA" },
  "982": { multiplier: 1.15, metro: "Everett area", state: "WA" },
  "983": { multiplier: 0.95, metro: "Tacoma", state: "WA" },
  "984": { multiplier: 1.20, metro: "Seattle area", state: "WA" },
  "985": { multiplier: 0.90, metro: "Olympia", state: "WA" },
  "986": { multiplier: 0.90, metro: "Vancouver, WA", state: "WA" },
  "988": { multiplier: 0.85, metro: "Wenatchee", state: "WA" },
  "989": { multiplier: 0.85, metro: "Yakima", state: "WA" },
  "990": { multiplier: 0.90, metro: "Spokane", state: "WA" },
  "991": { multiplier: 0.90, metro: "Spokane", state: "WA" },
  "992": { multiplier: 0.90, metro: "Spokane", state: "WA" },
  "993": { multiplier: 0.85, metro: "Pasco/Tri-Cities", state: "WA" },
  "994": { multiplier: 0.85, metro: "Lewiston, ID area", state: "ID" },
  "995": { multiplier: 1.20, metro: "Anchorage", state: "AK" },
  "996": { multiplier: 1.20, metro: "Anchorage area", state: "AK" },
  "997": { multiplier: 1.15, metro: "Fairbanks", state: "AK" },
  "998": { multiplier: 1.30, metro: "Juneau", state: "AK" },
  "999": { multiplier: 1.40, metro: "Ketchikan", state: "AK" },

  // ─────────────────────────────────────────────────────────────
  // COVERAGE COMPLETION — previously-missing assigned prefixes.
  // Three entire states (ND, SD, MT), Vermont, and the US territories
  // were absent, so their zips fell back to the coarse 1-digit bucket.
  // Added at metro granularity, same 0.75–1.50 best-fit scale.
  // (Unassigned 000–005 and military APO/FPO 090–098 / 962–966 are
  // intentionally omitted — no residents, no COLA to estimate.)
  // ─────────────────────────────────────────────────────────────

  // Puerto Rico + US Virgin Islands
  "006": { multiplier: 0.85, metro: "Puerto Rico", state: "PR" },
  "007": { multiplier: 0.80, metro: "Puerto Rico", state: "PR" },
  "008": { multiplier: 1.10, metro: "US Virgin Islands", state: "VI" },
  "009": { multiplier: 0.80, metro: "Puerto Rico", state: "PR" },

  // Vermont (050–059)
  "050": { multiplier: 0.95, metro: "White River Junction", state: "VT" },
  "051": { multiplier: 0.90, metro: "Vermont", state: "VT" },
  "052": { multiplier: 0.90, metro: "Bennington area", state: "VT" },
  "053": { multiplier: 0.90, metro: "Brattleboro", state: "VT" },
  "054": { multiplier: 1.00, metro: "Burlington", state: "VT" },
  "056": { multiplier: 0.90, metro: "Montpelier", state: "VT" },
  "057": { multiplier: 0.90, metro: "Rutland", state: "VT" },
  "058": { multiplier: 0.90, metro: "St. Johnsbury area", state: "VT" },
  "059": { multiplier: 0.90, metro: "Newport, VT", state: "VT" },

  // Massachusetts gap (Worcester / Fitchburg)
  "016": { multiplier: 1.05, metro: "Worcester/Fitchburg", state: "MA" },

  // West Virginia gap
  "269": { multiplier: 0.80, metro: "Lewisburg, WV", state: "WV" },

  // Florida Gulf-coast gaps
  "341": { multiplier: 1.00, metro: "Naples/Fort Myers", state: "FL" },
  "342": { multiplier: 1.00, metro: "Sarasota/Bradenton", state: "FL" },
  "344": { multiplier: 0.85, metro: "Gainesville area", state: "FL" },
  "346": { multiplier: 0.95, metro: "Tampa area", state: "FL" },
  "347": { multiplier: 0.95, metro: "Orlando area", state: "FL" },
  "349": { multiplier: 1.00, metro: "West Palm Beach area", state: "FL" },

  // Iowa gaps (Dubuque / Cedar Rapids / Waterloo)
  "521": { multiplier: 0.85, metro: "Dubuque", state: "IA" },
  "522": { multiplier: 0.85, metro: "Cedar Rapids area", state: "IA" },
  "523": { multiplier: 0.85, metro: "Cedar Rapids", state: "IA" },
  "524": { multiplier: 0.85, metro: "Iowa", state: "IA" },
  "525": { multiplier: 0.85, metro: "Waterloo", state: "IA" },
  "526": { multiplier: 0.85, metro: "Waterloo area", state: "IA" },
  "527": { multiplier: 0.85, metro: "Cedar Rapids area", state: "IA" },
  "528": { multiplier: 0.85, metro: "Cedar Rapids", state: "IA" },

  // Wisconsin gaps
  "533": { multiplier: 0.95, metro: "Milwaukee area", state: "WI" },
  "536": { multiplier: 0.90, metro: "Madison area", state: "WI" },

  // South Dakota (570–577) — entire state was missing
  "570": { multiplier: 0.85, metro: "Sioux Falls", state: "SD" },
  "571": { multiplier: 0.80, metro: "South Dakota", state: "SD" },
  "572": { multiplier: 0.80, metro: "South Dakota", state: "SD" },
  "573": { multiplier: 0.80, metro: "Mitchell, SD", state: "SD" },
  "574": { multiplier: 0.80, metro: "Aberdeen, SD", state: "SD" },
  "575": { multiplier: 0.80, metro: "Pierre, SD", state: "SD" },
  "576": { multiplier: 0.80, metro: "South Dakota", state: "SD" },
  "577": { multiplier: 0.85, metro: "Rapid City", state: "SD" },

  // North Dakota (580–588) — entire state was missing
  "580": { multiplier: 0.85, metro: "Fargo", state: "ND" },
  "581": { multiplier: 0.85, metro: "Fargo area", state: "ND" },
  "582": { multiplier: 0.85, metro: "Grand Forks", state: "ND" },
  "583": { multiplier: 0.85, metro: "Grand Forks area", state: "ND" },
  "584": { multiplier: 0.85, metro: "Devils Lake, ND", state: "ND" },
  "585": { multiplier: 0.85, metro: "Bismarck", state: "ND" },
  "586": { multiplier: 0.90, metro: "Dickinson, ND", state: "ND" },
  "587": { multiplier: 0.90, metro: "Minot", state: "ND" },
  "588": { multiplier: 0.95, metro: "Williston (Bakken)", state: "ND" },

  // Montana (590–599) — entire state was missing
  "590": { multiplier: 0.90, metro: "Billings", state: "MT" },
  "591": { multiplier: 0.90, metro: "Billings area", state: "MT" },
  "592": { multiplier: 0.85, metro: "Wolf Point, MT", state: "MT" },
  "593": { multiplier: 0.85, metro: "Miles City, MT", state: "MT" },
  "594": { multiplier: 0.90, metro: "Great Falls", state: "MT" },
  "595": { multiplier: 0.85, metro: "Havre, MT", state: "MT" },
  "596": { multiplier: 0.95, metro: "Helena", state: "MT" },
  "597": { multiplier: 0.90, metro: "Butte", state: "MT" },
  "598": { multiplier: 0.95, metro: "Missoula", state: "MT" },
  "599": { multiplier: 1.00, metro: "Kalispell/Flathead", state: "MT" },
};

/**
 * Look up region info for a given zip. Returns null if the zip's
 * 3-digit prefix isn't in our table — caller falls back to the
 * 1-digit prefix logic.
 */
export function regionForZip(zip: string): ZipRegion | null {
  if (!zip || zip.length < 3) return null;
  return ZIP_REGIONS[zip.slice(0, 3)] ?? null;
}
