import { RoseMark } from "@/components/Brand";

/**
 * Print-only letterhead. Renders as a clean header at the top of a PDF
 * when the user hits Cmd-P / Save as PDF. Hidden in normal screen view.
 *
 * The wrapper class `print-only` toggles display via globals.css —
 * `display: none` on screen, `display: block` in @media print.
 *
 * Pass the page title and (optionally) a subtitle so the printed
 * document feels like a real document instead of a screenshot.
 *
 * Example:
 *   <PrintHeader title="Arrangement-meeting cheat sheet" />
 *   <PrintHeader
 *     title="Quote comparison"
 *     subtitle="Three quotes received between May 6–9, 2026"
 *   />
 */
export function PrintHeader({
  title,
  subtitle,
}: {
  title: string;
  subtitle?: string;
}) {
  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <div className="print-only mb-6 pb-4 border-b border-gray-300">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <RoseMark size={28} />
          <span
            className="font-serif text-lg leading-none"
            style={{ color: "#111" }}
          >
            Honest Funeral
          </span>
        </div>
        <div className="text-xs" style={{ color: "#555" }}>
          {today}
        </div>
      </div>
      <h1
        className="mt-3 text-2xl font-serif"
        style={{ color: "#111", marginBottom: 0 }}
      >
        {title}
      </h1>
      {subtitle ? (
        <p className="text-sm mt-1" style={{ color: "#555" }}>
          {subtitle}
        </p>
      ) : null}
    </div>
  );
}

/**
 * Print-only footer. Sticks brand + URL at the bottom of every printed
 * document so families know where this came from when they pull it out
 * of a folder six months later.
 */
export function PrintFooter() {
  return (
    <div
      className="print-only mt-8 pt-4 border-t border-gray-300 text-xs"
      style={{ color: "#666" }}
    >
      <p>
        Generated by Honest Funeral · honestfuneral.co · A consumer
        advocate for families. Information here is general guidance,
        not legal, medical, or financial advice.
      </p>
    </div>
  );
}
