import { describe, it, expect } from "vitest";
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

/**
 * BOOTSTRAP.sql is generated (not hand-written) by build-bootstrap-sql.mjs,
 * but nothing ever enforced that someone actually re-ran it after adding a
 * migration — it silently drifted for months, missing 9 migrations' worth of
 * schema, while docs/PROD_SETUP.md told founders it was always safe to paste
 * the "current" file. This test regenerates the expected content the same
 * way the script does and fails loudly if the committed file disagrees.
 */
describe("supabase/BOOTSTRAP.sql", () => {
  it("matches schema.sql + every migration, freshly concatenated", () => {
    const supa = join(process.cwd(), "supabase");
    const migDir = join(supa, "migrations");
    const migrations = readdirSync(migDir)
      .filter((f) => f.endsWith(".sql"))
      .sort();

    const bar = "=".repeat(78);
    let expected = `-- ${bar}
-- Honest Funeral — PRODUCTION DATABASE BOOTSTRAP
-- GENERATED by scripts/build-bootstrap-sql.mjs — do not hand-edit.
-- Re-generate:  node scripts/build-bootstrap-sql.mjs
--
-- HOW TO USE: open a fresh prod Supabase project → SQL Editor → paste this
-- ENTIRE file → Run. It applies schema.sql then every migration in order.
-- Idempotent, so safe to re-run. See docs/PROD_SETUP.md for the full checklist
-- (storage bucket, magic-link auth, env vars, DNS) — this file is just the DB.
-- ${bar}
`;
    const section = (title: string, body: string) => {
      expected += `\n\n-- ${bar}\n-- ${title}\n-- ${bar}\n\n${body.trim()}\n`;
    };
    section("schema.sql", readFileSync(join(supa, "schema.sql"), "utf8"));
    for (const m of migrations) {
      section(`migrations/${m}`, readFileSync(join(migDir, m), "utf8"));
    }

    const actual = readFileSync(join(supa, "BOOTSTRAP.sql"), "utf8");
    expect(actual).toBe(expected);
  });
});
